### ISSUE TITLE
Is it possible for togglem to toggle layer when key pressed, not key released?

### ISSUE THREAD

**Issue by adusamr** [rvaiya/keyd#683] opened 2024-03-04 04:15 UTC
```
[ids]
*

[layer_b]

[control]
a = 0
b = togglem(layer_b, b)

[layer_b+control]
a = 1
b = clear()
```

Using above .conf, when I hold ctrl+b, and while holding them press  a, keyd emits "b0". Then release b and press a, keyd emits "1".
This indicate togglem emits the macro when the key is pressed but toggles layer when the key is released.

I want to toggle the layer when the key is pressed, immediately after the macro is emitted.

Is this possible?
Or not, this may be a feature request.

**Comment by rvaiya** [comment] 2024-03-06 23:16
I believe there was a reason I originally implemented toggle on key release, but I can't seem to remember it at the moment. I don't believe there is another way to achieve what you have described.

I've tentatively changed the default behaviour to eagerly toggle layers on key down in the latest commit.

@nsbgn What do you think?

**Comment by nsbgn** [comment] 2024-03-07 12:52
I can't think of a reason why one might *not* want to execute the toggle asap. Doesn't mean there is none, but I guess we'll find out if there is?

Fwiw, I wouldn't expect the next key be something different when it overlaps with the key that activated the toggle, so the new behaviour is less surprising.

**Comment by rvaiya** [comment] 2024-03-08 02:35
Oops, looks like I forgot to push. I'm closing this for now. Feel free to reopen it if the issue is unresolved.

**Closed by rvaiya** 2024-03-08 02:35 UTC

**Comment by adusamr** [comment] 2024-03-08 07:49
I'm testing it and it's working perfectly as I want. Thanks!
