### ISSUE TITLE
rightmeta is mapped to leftmeta when any config is applied by keyd.

### ISSUE THREAD

**Issue by hillyu** [rvaiya/keyd#86] opened 2022-01-05 04:41 UTC
As long as I have a config enforced and the keyboard is "managed" by keyd, my `rightmeta` will be recognized as `leftmeta`
Tried empty config, issue persists.
```bash
$ sudo journalctl -u keyd|tail -n7
Jan 05 12:30:18 Xin systemd[1]: Stopped key remapping daemon.
Jan 05 12:30:47 Xin systemd[1]: Started key remapping daemon.
Jan 05 12:30:47 Xin keyd[11244]: Starting keyd v2.1.0-beta (57f9aa5804c566ad877cba987beec2bcd214d612).
Jan 05 12:30:48 Xin keyd[11244]: No config found for Logitech G304 (046d:4074)
Jan 05 12:30:48 Xin keyd[11244]: No config found for DOT@LOFREE (05ac:0255)
Jan 05 12:30:48 Xin keyd[11244]: No config found for AT Translated Set 2 keyboard (0001:0001)
Jan 05 12:30:48 Xin keyd[11244]: No config found for LogiOps Virtual Input (0000:0000)
# hill @ Xin in ~ [12:31:04]
$ keyd -m
DOT@LOFREE      05ac:0255       rightmeta down
DOT@LOFREE      05ac:0255       rightmeta up
DOT@LOFREE      05ac:0255       rightmeta down
```
when empty main.conf applied, rightmeta turned into leftmeta:
```
[ids]

*
-046d:4074
-0000:0000

[main]

```
```bash
$ sudo journalctl -u keyd|tail -n7
Jan 05 12:32:16 Xin systemd[1]: Started key remapping daemon.
Jan 05 12:32:16 Xin keyd[11713]: Starting keyd v2.1.0-beta (57f9aa5804c566ad877cba987beec2bcd214d612).
Jan 05 12:32:16 Xin keyd[11713]: Parsing /etc/keyd/01-main.conf
Jan 05 12:32:16 Xin keyd[11713]: No config found for Logitech G304 (046d:4074)
Jan 05 12:32:16 Xin keyd[11713]: Managing DOT@LOFREE (05ac:0255) (/etc/keyd/01-main.conf)
Jan 05 12:32:16 Xin keyd[11713]: Managing AT Translated Set 2 keyboard (0001:0001) (/etc/keyd/01-main.conf)
Jan 05 12:32:17 Xin keyd[11713]: No config found for LogiOps Virtual Input (0000:0000)
# hill @ Xin in /etc/keyd [12:32:20]
$ keyd -m
keyd virtual keyboard   0fac:0ade       enter up
keyd virtual keyboard   0fac:0ade       leftmeta down
keyd virtual keyboard   0fac:0ade       leftmeta up
```

**Comment by rvaiya** [comment] 2022-01-05 06:59
Yes, this is by design. 

In most cases this shouldn't be an issue unless you rely on some piece of software which ignores the display server and actually distinguishes between `rightmeta` and `leftmeta`. This is because most software only cares about the 'modifier state' which doesn't distinguish between the right and left version of the keys. The only place it might be relevant is if you are remapping something in your window manager, in which case you can just use another code and explicitly assign it to  `rightmeta` in your config.

It would help to know what your end goal is. See also #85.

**Comment by hillyu** [comment] 2022-01-05 09:16
good to know, and thanks for the fast reply, I used my rightmeta, rightalt, and menu as ISO_LEVEL3_SHIFT (mod5) in my window manager. After knowing the way setting this, I just  did following and all problem solved:
`rightmeta = layer(altgr)`

**Comment by hillyu** [comment] 2022-01-05 09:37
with you iso_level3_shift   #84 , I can just do:
`rightmeta = iso-level3-shift`
Thanks again for the great work!

**Closed** 2022-01-05 18:28 UTC
