### ISSUE TITLE
Conflicts between layers e.g. left shift and right shift

### ISSUE THREAD

**Issue by adast9** [rvaiya/keyd#85] opened 2022-01-04 18:20 UTC
My config can be found [here](https://raw.githubusercontent.com/adamstuck/dotfiles/30c28d7251260dd9b801c801be77fd3588e5f07f/.config/keyd/default.conf), although this issue seems to occur in keyd's default behavior.

Left shift down
Right shift down
Left shift up

I am still holding shift but keyd doesn't recognize it that way, so typed letters come out in lower case.

**Comment by rvaiya** [comment] 2022-01-04 21:24
This happens because `rightshift` and `leftshift` are both mapped to `layer(shift)`. The distinction between the different shift keys is consequently eliminated which means that a key up event from one of them will affect the other. 

I was aware of this when I made that design decision but didn't think anyone would ever simultaneously activate both modifier keys :P. Is this a real problem in your day to day use? If so, there are some potential solutions I could implement (though they come with caveats).

**Comment by rvaiya** [comment] 2022-01-04 21:32
One way to avoid this is to assign `rightshift` to its own layer based on shift.

E.G
```
rightshift = layer(rightshift)

[rightshift:S]
```

A more oblique way to achieve the same thing is just `rightshift = layer(S)` since `S` is a valid default layer that is distinct from `shift`, though I would favour the above approach rather than rely on such obscure behaviour :P.

**Comment by adamstuck** [comment] 2022-01-04 21:45
Okay thanks for the explanation. This isn't really a problem for me in my every day use but just something I noticed and wanted to see if it was intentional or not 😄 . Though I wonder if it would be possible to let keys use their regular behaviour unless

**Comment by rvaiya** [comment] 2022-01-04 22:07
> Though I'm wondering: would it be possible to just use a keys true default behaviour when it hasn't explicity been mentioned in a .conf?

The modifiers are assigned to layers by default for 3 main reasons:

1. It forces the user to think in terms of layers rather than modifiers.
2. It makes the implementation easier :P.
3. It allows the user to extend default modifiers without explicitly assigning them to layers in a way which is intuitive and concise even without understanding the semantics of the config file.

   E.G

   ```
   [ids]
   *

   [shift]

   a = C-a
   ```

is a completely valid config and does what one would expect even if they didn't know anything about layers.

> Could you just make it so that is simply ignored by keyd and is processed by tty, X, etc, unless it is actually included in the conf?

In most cases the default behaviour does what the user would expect and provides additional flexiblity, but does admittedly come at the cost of breaking some obscure corner cases. Assigning directly to modifier key codes like `rightshift` and `righmeta` is not well supported outside of macros and I am considering issuing a warning or possibly eliminating them entirely.

**Comment by adamstuck** [comment] 2022-01-04 22:10
I'll close this seeing as it's a non issue but thanks for the detailed explanation.

**Comment by rvaiya** [comment] 2022-01-05 00:04
No worries. Don't hesitate to let me know if you encounter any other issues or non intuitive behaviour. This sort of feedback is useful as it is always useful to know which of my assumptions hold in the real world :P.

**Comment by andrey-shigantsov** [comment] 2022-02-02 05:28
> One way to avoid this
> ```
> rightshift = layer(rightshift)
> [rightshift:S]
> ```

Looks like this is the solution for me. I will test.

> It would help if I knew what specific problem you are trying to solve.

The problem is that when you type quickly with ten-finger blind typing, you often have to change the side of the modifier keys and the default behavior breaks the control.

**Comment by adamstuck** [comment] 2022-02-02 14:31
I'm not sure if this is due to the same issue but I'll post my question here.

In my config I have a layer for meta and one for meta+(left)shift.
If I am in the meta+shift layer and I release shift I want to return to the meta layer.
If I release meta I want to return to shift.
Is this possible?

**Comment by adamstuck** [comment] 2022-02-02 14:31
I'm not sure if this is due to the same issue but I'll post my question here.

In my config I have a layer for meta and one for meta+(left)shift.
If I am in the meta+shift layer and I release shift, I want to return to the meta layer.
If I release meta, I want to return to the shift layer.
Is this possible?

**Comment by rvaiya** [comment] 2022-02-02 18:39
> If I release meta, I want to return to the shift layer.

Unfortunately there isn't a good way to achieve this using normal layers semantics. I've been toying which some ideas which might make this kind of thing possible, but I don't know if I will end up implementing them. If you feel strongly about this, feel free to create another issue.

**Comment by rvaiya** [comment] 2022-03-22 03:04
@adast9 

> In my config I have a layer for meta and one for meta+(left)shift.
> If I am in the meta+shift layer and I release shift, I want to return to the meta layer.
> If I release meta, I want to return to the shift layer.
> Is this possible?

This is now possible using composite layers. See the man page for details. I'm closing this issue, but feel free to open another one if you feel your issue is unresolved.

**Closed by rvaiya** 2022-03-22 03:04 UTC
