### ISSUE TITLE
"space = overload(M, space)" inserts Ctrl

### ISSUE THREAD

**Issue by funcrab** [rvaiya/keyd#157] opened 2022-03-19 12:01 UTC
When I entered `space` with the following settings, there was a `leftcontrol` mixed in the middle.

```
[main]
space = overload(M, space)
```

```
keyd virtual keyboard   xxxx:xxxx       leftmeta down
keyd virtual keyboard   xxxx:xxxx       leftcontrol down
keyd virtual keyboard   xxxx:xxxx       leftmeta up
keyd virtual keyboard   xxxx:xxxx       leftcontrol up
keyd virtual keyboard   xxxx:xxxx       space down
keyd virtual keyboard   xxxx:xxxx       space up
```

I am having trouble using `overload(<layer>,<keyseq>[,<timeout>])` timeouts because sometimes the timing does not work properly. I would be happy to see the following as it is.
```
keyd virtual keyboard   xxxx:xxxx       leftmeta down
keyd virtual keyboard   xxxx:xxxx       leftmeta up
keyd virtual keyboard   xxxx:xxxx       space down
keyd virtual keyboard   xxxx:xxxx       space up
```
How do I do it?

**Comment by rvaiya** [comment] 2022-03-19 20:11
This is by design, it prevents the operating system from processing unintentional `meta` keypresses (see 076a1868e5 for details). Is it causing a problem? The additional keystrokes shouldn't have an adverse effect.

**Comment by funcrab** [comment] 2022-03-20 06:00
Thank you. I knew it was a specification that had been considered.

The problem in my case happened when I was using this.
https://github.com/ilyazzz/sway-marker

I believe the behavior is as follows

1. Key press: meta+semicolon
2. Activated by swaywm: sway-maker mark
3. Release key: space
-> Ctrl cancels sway-maker

**Comment by rvaiya** [comment] 2022-03-20 08:29
My understanding is that you want `meta+space`

to produce the following sequence:

	meta down
	space down
	space up
	meta up

while preserving the behaviour of `space = overload(M, space)`. To achieve this, you can just explicitly remap space within the default meta layer.

E.G

[meta]

space = M-space

**Comment by funcrab** [comment] 2022-03-20 09:43
> My understanding is that you want meta+space

No, I was simply curious about the Ctrl when releasing the `space = overload(M, space)` key.
If it is not an unintentional glitch, no problem.
My problem above is not serious and I have already found an alternative, so feel free to close it.
I have replaced the `M` to `meta`.
Thanks again for all your cool developments.

**Comment by rvaiya** [comment] 2022-03-21 00:26
I'm closing this for now. Feel free to reopen it if you feel the problem is unresolved.

**Closed by rvaiya** 2022-03-21 00:26 UTC

**Comment by funcrab** [comment] 2022-03-22 16:44
This problem has been resolved as follows. I'm grad.
```
$ keyd --version
keyd v2.3.0-rc (6581f36)
$
```

```
space = timeout(overload(meta, space), 1000, space)
```

```
keyd virtual device     xxxx:xxxx       leftmeta down
keyd virtual device     xxxx:xxxx       ; down
keyd virtual device     xxxx:xxxx       ; up
keyd virtual device     xxxx:xxxx       leftmeta up
```
It does not change the behavior of the `space` alone, 
```
keyd virtual device     xxxx:xxxx       leftmeta down
keyd virtual device     xxxx:xxxx       leftcontrol down
keyd virtual device     xxxx:xxxx       leftmeta up
keyd virtual device     xxxx:xxxx       leftcontrol up
keyd virtual device     xxxx:xxxx       space down
keyd virtual device     xxxx:xxxx       space up
```
but it is enough to solve my case.
