### ISSUE TITLE
No output from keyd devices when convertible laptop in tablet mode

### ISSUE THREAD

**Issue by blepabyte** [rvaiya/keyd#353] opened 2022-10-02 03:22 UTC
Device: Thinkpad X1 Yoga (Gen 6)
GNOME 42.4, Wayland
Keyd versions: Tried 2.4.2 and from latest commit

Most 2-in-1 devices automatically disable the internal keyboard when "flipped", but when `keyd` is running, external (USB and wireless) keyboards specified in the configuration file also stop working. 

Keystrokes show up in keyd's monitor mode as from `keyd virtual keyboard` but not in any applications or `libinput debug-events` until either keyd is stopped, or the device is returned to laptop mode. 

After some digging around, this behaviour seems to be an unintended consequence of this line:
https://github.com/rvaiya/keyd/blob/c1ba867e6fcb9a175227bafa87cf57957ce28816/keyd.quirks#L4

Changing internal to external and rebooting seemed to fix it for me, though not sure if that's the most appropriate solution in keyd.

**Comment by rvaiya** [comment] 2022-10-03 08:40
This appears to be the opposite of #66. I probably should have gone with my initial instinct and left this up to the user (i.e not shipped a quirks file).

@canadaduane How do you feel about this?

**Comment by canadaduane** [comment] 2022-10-04 22:35
This is a bit tricky, as the "internal" designation allows keyboard & touchpad to coordinate, but it's really just a happy side-effect. I wish there were a better way for a virtual keyboard to "pair" with a touchpad. Perhaps we should ask @whot for guidance. He may know of a more explicit way to tell libinput to allow a virtual keyboard to inherit this pairing?

**Comment by rvaiya** [comment] 2022-10-04 23:20
The fundamental problem is that the virtual device created by keyd is conceptually neither an internal keyboard nor an external one. There is no reason to treat it as one or the other, since it may well subsume both. The correct thing to do is likely to just make the user aware of this and let them handle it accordingly.

**Comment by canadaduane** [comment] 2022-10-04 23:48
Right, I think we're agreeing but I'm suggesting there may be a better outcome if we go one step further and (if necessary) influence the udev or libinput standards to include a way for keyd to communicate this edge case. If there's a way for it to "do the right thing" for people without requiring manual intervention this would be a win (especially in the case of a laptop, which I wouldn't say is unusual).

For example: what if we could add an attribute to the udev system for the real keyboard (e.g. `E: DWT_PAIR=/dev/input/event6`) that suggests the device (keyboard) be "paired" with the touchpad for "Disable While Typing". Then, when keyd comes along and sees this attribute, it could add it to the udev system for the virtual keyboard. Finally, if `libinput` were modified to understand this pairing suggestion, it could "do the right thing" without a special local quirks file.

**Comment by rvaiya** [comment] 2022-10-05 01:10
I believe that would require cross distro coordination (or maybe just systemd cooperation?). I assume the reason libinput ships with a bunch of quarks files rather than exclusively relying on udev properties is because this is difficult to achieve in practice.  

There also remains the issue that keyd presents as a single virtual device which must either be treated as an integrated or external device. A simpler solution would be to create a dedicated virtual device for each input device which mirrors its properties, but that has other implications. Finally, udev has been deliberately excised from the code for portability reasons.

As far as I can see, there isn't a good or easy solution to this problem, but I should like to be proven wrong :).

**Comment by whot** [comment] 2022-11-18 04:46
The immediate workaround should be to add `ModelTabletModeNoSuspend=1` to the quirks. That tells libinput that this device must not be suspended in tablet mode.

As for the rest - yes, the problem is very much that libinput is a *hardware* abstraction stack. Software devices make things difficult since we can't use any heuristics and/or our existing heuristics break. There's no good solution here I can see, adding a "random" set of configuration options to libinput (via udev or whatever) won't really fix the problem because the next use-case will have some different requirement. So we'll end up with lots of configurations that all do one niche thing, likely conflict with each other. And, the biggest concern (for me :smile:) it will push the testing effort of all the combinations onto libinput.

**Comment by rvaiya** [comment] 2022-11-19 03:16
From the input tsar himself (big fan btw :P)! I suppose that settles the question. I've stopped shipping the quirks file and am closing the issue for now.

**Closed by rvaiya** 2022-11-19 03:16 UTC

**Comment by whot** [comment] 2022-11-21 00:00
Just as a closing comment: we've been working on [libei](https://gitlab.freedesktop.org/libinput/libei/) for quite a while now and most of the pieces are slowly falling into place. Unlike libinput which is a hardware stack, libei is a software input stack. Or,  to be more precise, it's a transport layer for logical input events. You send a click, you get a click. How that click is generated is up to you as the sender.

The motivation for libei are two applications, xdotool and [InputLeap](https://github.com/input-leap/input-leap/) (formerly barrier, formerly synergy). keyd *may* be a fit as well although libei's integration into the compositor is very specifically aimed at applications sending events, so it doesn't have the "always works" guarantees you'd get by running as root and injecting via uinput. And of course it depends on the compositor actually supporting libei.

**Comment by rvaiya** [comment] 2022-11-21 09:35
> Just as a closing comment: we've been working on libei for quite a while now
> and most of the pieces are slowly falling into place. Unlike libinput which is
> a hardware stack, libei is a software input stack. Or, to be more precise, it's
> a transport layer for logical input events. You send a click, you get a click.
> How that click is generated is up to you as the sender.

Great :). I haven't had a chance to look through the API yet, but keyd would also need the ability to grab the existing input devices. Is this something that would be supported? How does the project compare to experimental wayland protocols like virtual-keyboard-unstable-v1?

keyd is designed to support multiple backends (I have macos and windows prototypes sitting in a private repo), and I would certainly be interested in supporting a rootless version which can take advantage of display server input mechanisms.

**Comment by whot** [comment] 2022-11-21 10:35
>  but keyd would also need the ability to grab the existing input devices. Is this something that would be supported?

completely unrelated to libei which doesn't care about *how* you (keyd) generate the emulated input events. so there's no direct support but you can do it yourself. best summary is that libei replaces all the uinput parts in keyd, but nothing else.

> virtual-keyboard-unstable-v1

there's large overlap here, the difference is in design philosophy. libei is designed to allow applications to run via flatpak/portals. This isn't doable, or at least not easily, via a wayland protocol. so yes, very much a case of two competing standards and neither will be supported by all compositors (GNOME won't have virtual keyboard, sway won't have libei).

 > keyd is designed to support multiple backends 

in that case you can *probably* (without knowing the code) add a libei backend in addition to the uinput one and re-use everything else, so integration should be fairly easy.
