### ISSUE TITLE
Compose codepoints and line feed leak to output

### ISSUE THREAD

**Issue by demiaus** [rvaiya/keyd#285] opened 2022-08-13 02:29 UTC
3 levels:

1. Fine: in terminal you can notice that holding ö or ä down outputs characters slower than with other keys.
2. Bit annoying: Visual artefacts flicker but output stays intact. (See gif).
3. Worst: pronounced artefacts and output is mangled.

This is the output when I wrote `mitäs tässä` into signal-desktop messenger's input field
```
mit
s t
ss
ä0010001000ä0010001000ä
```
![keyd](https://user-images.githubusercontent.com/76442633/184464519-914c19e2-018c-43c2-b659-94c279dd669b.gif)

**Comment by rvaiya** [comment] 2022-08-14 23:10
This is more likely another artifact of chrome's broken XCompose handling.

@krumeluu 

Can you try the latest commit?

**Comment by krumeluu** [comment] 2022-08-15 00:24
> Can you try the latest commit?

The latest commit completely fixed the issue while using [Signal-Desktop](https://github.com/signalapp/Signal-Desktop), with which the problem was the worst. I don't know what this might imply..
The problem persist with browsers I've tested, Librewolf, Firefox and Chromium.

> Try setting the macro_sequence_timeout parameter in the global section,

This didn't solve the issue.

When I restart the daemon, sometimes systemd journal fills with this:
```
.
.
Aug 15 03:18:11 user keyd[4025]: Unrecognized EV_ABS code: 54
Aug 15 03:18:11 user keyd[4025]: Unrecognized EV_ABS code: 53
Aug 15 03:18:11 user keyd[4025]: Unrecognized EV_ABS code: 24
Aug 15 03:18:11 user keyd[4025]: Unrecognized EV_ABS code: 54
.
.
```
10-100 rows per second, but I cannot reproduce it reliably.

**Comment by rvaiya** [comment] 2022-08-15 00:27
@krumeluu Did you try restarting your browsers?

> Aug 15 03:18:11 user keyd[4025]: Unrecognized EV_ABS code: 54

You can safely ignore these, they are unrelated. I would also advise you to remove `macro_sequence_timeout = 2000` unless you need it, as it shouldn't have any effect.

**Comment by krumeluu** [comment] 2022-08-15 01:01
> Did you try restarting your browsers?

Yes, and to make sure rebooted. I've also removed the macro timeout.
Upon reboot I got new kind of journal entries:
```
Aug 15 03:53:08 user keyd[562]: ioctl EVIOCGNAME: Inappropriate ioctl for device
Aug 15 03:53:08 user keyd[562]: ioctl: Inappropriate ioctl for device
Aug 15 03:53:08 user keyd[562]: ioctl EVIOCGNAME: Inappropriate ioctl for device
Aug 15 03:53:09 user keyd[562]: ioctl: Invalid argument
Aug 15 03:53:09 user keyd[562]: ioctl EVIOCGNAME: Invalid argument
Aug 15 03:53:09 user keyd[562]: failed to open /dev/input/by-id
Aug 15 03:53:10 user keyd[562]: ioctl: Inappropriate ioctl for device
Aug 15 03:53:10 user keyd[562]: ioctl EVIOCGNAME: Inappropriate ioctl for device
```
When I restart the daemon, those don't resurfase.

**Comment by rvaiya** [comment] 2022-08-15 03:29
By 'the problem persists' are you referring to the mangled output or just the delay/artifacts? The patch should have completely fixed the former. Can you post your DE/OS/Browser Version?

**Comment by krumeluu** [comment] 2022-08-24 07:54
Yes, the patch fixed the former, only delay/flickering persists. I remember Chromium being affected when I tested a week ago, but now the flickering is gone with Chromium 104.0. (Maybe there was an update during the last week.). Only slight sluggishness remains (virtually fixed in my books).

With Firefox fork Librewolf 103.0.2 and freshly installed unmodified Firefox 104.0. the flickering is still present. 

Arch Linux, tested on kernels 5.19.3.arch1-1 and 5.19.3.zen1-1
WM: dwm 6.3.

With Awesome WM behaviour was the same, but Awesome and dwm are related so I better test with something else still when I get to it.

**Comment by krumeluu** [comment] 2022-08-26 10:21
Also in apps `steam` and `spotify` the output is completely garbled. I don't really know about these things, but is this something to do with electron?

**Comment by rvaiya** [comment] 2022-08-28 07:55
> Also in apps steam and spotify the output is completely garbled. I don't really know about these things, but is this something to do with electron?

Probably. Chromium's XCompose handling is broken, which presumably also affects electron apps. 

I've shortened the length of the compose sequences in an attempt to reduce visual latency. Can you see if the latest commit makes a difference?

**Comment by krumeluu** [comment] 2022-08-29 15:40
It seems the latest commit reduces visual glitches; the seem to go by faster. Also (unexpectedly?) Steam now receives input flawlessly. Spotify still not: "ö ä Ö Ä" produces "03a 02s 02e 01w"

**Comment by rvaiya** [comment] 2022-11-19 03:27
Closing due to inactivity.

**Closed by rvaiya** 2022-11-19 03:27 UTC
Labels: todo, unicode, optimization
