### ISSUE TITLE
Control_R maps to Control_L

### ISSUE THREAD

**Issue by sarmong** [rvaiya/keyd#185] opened 2022-04-11 17:09 UTC
When keyd is running, my `Control_R` key becomes `Control_L` key even with an empty `default.conf`

Before:
```
KeyRelease event, serial 37, synthetic NO, window 0x4e00001,
    root 0x799, subw 0x0, time 13887626, (-348,330), root:(1392,364),
    state 0x4, keycode 105 (keysym 0xffe4, Control_R), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

After:

```
KeyRelease event, serial 37, synthetic NO, window 0x4e00001,
    root 0x799, subw 0x0, time 14012974, (-335,888), root:(1405,922),
    state 0x4, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

**Comment by rvaiya** [comment] 2022-04-11 18:23
This is by design, see #114. Is this a problem for you?

**Comment by sarmong** [comment] 2022-04-11 19:32
But it _might_ be an issue for some users. E.g. since Right Control is rarely used, some users might want to remap to a different key. For example,Meta key

**Comment by rvaiya** [comment] 2022-04-11 21:28
As mentioned in the other thread, you can still remap `rightcontrol` (e.g `rightcontrol = x`). I'm closing this for now, but feel free to reopen it if you feel the issue is unsolved.

**Closed by rvaiya** 2022-04-11 21:28 UTC

**Comment by ernstki** [comment] 2025-11-21 12:25
[This comment](https://github.com/rvaiya/keyd/issues/1119#issuecomment-3330299470) from #1119 is a useful reference, if you want to understand what the defaults are. @rvaiya It also appears to be a duplicate of this issue and #114, fundamentally.
