### ISSUE TITLE
Can't map to R'

### ISSUE THREAD

**Issue by Louis-dM** [rvaiya/keyd#117] opened 2022-01-22 17:38 UTC
I'm trying to map a key to type `R'` (capital R followed by an apostrophe). None of the following work:

```
k = macro(capslock r capslock ')
k = macro(shift+r ')
k = macro(R')
k = macro(R ')
k = macro(S-r ')
```
These all produce `r'`, except for the second one, which produces `k`.

Is there a way to achieve this?

**Comment by rvaiya** [comment] 2022-01-22 20:28
Odd, these all work for me. Can you post the output of `keyd -m` when you press k?

**Comment by Louis-dM** [comment] 2022-01-22 22:11
Here's a reduced version of the config I was using which has the same effect. I'm using alt+capslock to enter the layout.

```
[ids]

*

[main]

[alt]

capslock = layout(virtualcube)

[virtualcube:layout]

capslock = layout(main)

# the `i` remap is just to check I'm in the right layout
i = R
k = macro(R')
```

**Comment by rvaiya** [comment] 2022-01-22 22:30
> Output of sudo keyd -m when I press k:
> ...

This the expected output. keyd seems to be doing its job.

I've also tested this on my machine and it outputs R' as expected.  My guess is that something higher up in your input stack is causing interference, keyd is just a keycode->keycode remapping tool. This could be a display server tool like xcape or your layout (use qwerty for best results and then do any remapping in keyd).

**Comment by Louis-dM** [comment] 2022-01-22 23:32
I didn't have any other key mapping software installed, and I disabled my non-QWERTY layout, and it didn't change anything, so I did some more experimenting. The problem seems to be Wayland. When I'm logged in on X11 it works perfectly and produces `R'`.

Is there a workaround for Wayland?

**Comment by rvaiya** [comment] 2022-01-22 23:42
I just tried this under sway without issue. What compositor are you running? It is more likely to be something in your config logic than a bug in the compositor. Most wayland implementations use libinput, to which keyd should be invisible. 

My advice would be to be to create a new user and test with an empty config.

**Comment by rvaiya** [comment] 2022-01-22 23:49
The output of ` sudo journalctl -n 50 -u keyd --no-pager` might also provide some insight.

**Comment by Louis-dM** [comment] 2022-01-23 22:06
> I just tried this under sway without issue. What compositor are you running? It is more likely to be something in your config logic than a bug in the compositor. Most wayland implementations use libinput, to which keyd should be invisible.
> 
> My advice would be to be to create a new user and test with an empty config.

I'm sort of new to Linux, so I'm not 100% certain this is the right answer, but I'm pretty sure my compositor is Mutter. (I'm using Gnome on Fedora, and from reading around a bit it seems Mutter is the compositor used with Gnome).

I've noticed something VERY strange happening this morning when I came back to testing things out... it's now working, but only in my terminal (Kitty). In Firefox, Libreoffice Writer and Gnome Terminal it's still only giving me `r'`. And even stranger is that it also sometimes (but not always) disables a key, and it only ever seems to be `i` or `k`. And `sudo keyd -m` registers the keypress, it just has no effect.

`sudo journalctl -n 50 -u keyd --no-pager` doesn't seem to give any hints:
```Jan 23 11:54:06 louis-GA401IU keyd[12331]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:54:07 louis-GA401IU keyd[12331]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:54:44 louis-GA401IU keyd[12331]: cleaning up and terminating...
Jan 23 11:54:44 louis-GA401IU systemd[1]: Stopping key remapping daemon...
Jan 23 11:54:44 louis-GA401IU systemd[1]: keyd.service: Main process exited, code=exited, status=15/n/a
Jan 23 11:54:44 louis-GA401IU systemd[1]: keyd.service: Failed with result 'exit-code'.
Jan 23 11:54:44 louis-GA401IU systemd[1]: Stopped key remapping daemon.
Jan 23 11:54:44 louis-GA401IU systemd[1]: Started key remapping daemon.
Jan 23 11:54:44 louis-GA401IU keyd[12409]: Starting keyd v2.2.4-beta (d475661f9361fa24f166c9b5ed0b660b96a055b3).
Jan 23 11:54:44 louis-GA401IU keyd[12409]: Parsing /etc/keyd/default.conf
Jan 23 11:54:44 louis-GA401IU keyd[12409]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:54:44 louis-GA401IU keyd[12409]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:55:49 louis-GA401IU keyd[12409]: src/keyd.c:476: Termination key sequence triggered (backspace+escape+enter), terminating.
Jan 23 11:55:49 louis-GA401IU keyd[12409]: cleaning up and terminating...
Jan 23 11:55:49 louis-GA401IU systemd[1]: keyd.service: Main process exited, code=exited, status=255/EXCEPTION
Jan 23 11:55:49 louis-GA401IU systemd[1]: keyd.service: Failed with result 'exit-code'.
Jan 23 11:56:07 louis-GA401IU systemd[1]: Started key remapping daemon.
Jan 23 11:56:07 louis-GA401IU keyd[12471]: Starting keyd v2.2.4-beta (d475661f9361fa24f166c9b5ed0b660b96a055b3).
Jan 23 11:56:07 louis-GA401IU keyd[12471]: Parsing /etc/keyd/default.conf
Jan 23 11:56:07 louis-GA401IU keyd[12471]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:56:07 louis-GA401IU keyd[12471]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:56:11 louis-GA401IU keyd[12471]: cleaning up and terminating...
Jan 23 11:56:11 louis-GA401IU systemd[1]: Stopping key remapping daemon...
Jan 23 11:56:11 louis-GA401IU systemd[1]: keyd.service: Main process exited, code=exited, status=15/n/a
Jan 23 11:56:11 louis-GA401IU systemd[1]: keyd.service: Failed with result 'exit-code'.
Jan 23 11:56:11 louis-GA401IU systemd[1]: Stopped key remapping daemon.
Jan 23 11:56:11 louis-GA401IU systemd[1]: Started key remapping daemon.
Jan 23 11:56:11 louis-GA401IU keyd[12511]: Starting keyd v2.2.4-beta (d475661f9361fa24f166c9b5ed0b660b96a055b3).
Jan 23 11:56:11 louis-GA401IU keyd[12511]: Parsing /etc/keyd/default.conf
Jan 23 11:56:11 louis-GA401IU keyd[12511]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:56:11 louis-GA401IU keyd[12511]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:56:15 louis-GA401IU keyd[12511]: src/keyd.c:476: Termination key sequence triggered (backspace+escape+enter), terminating.
Jan 23 11:56:15 louis-GA401IU keyd[12511]: cleaning up and terminating...
Jan 23 11:56:15 louis-GA401IU systemd[1]: keyd.service: Main process exited, code=exited, status=255/EXCEPTION
Jan 23 11:56:15 louis-GA401IU systemd[1]: keyd.service: Failed with result 'exit-code'.
Jan 23 11:56:52 louis-GA401IU systemd[1]: Started key remapping daemon.
Jan 23 11:56:52 louis-GA401IU keyd[12585]: Starting keyd v2.2.4-beta (d475661f9361fa24f166c9b5ed0b660b96a055b3).
Jan 23 11:56:52 louis-GA401IU keyd[12585]: Parsing /etc/keyd/default.conf
Jan 23 11:56:52 louis-GA401IU keyd[12585]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:56:52 louis-GA401IU keyd[12585]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:57:57 louis-GA401IU keyd[12585]: cleaning up and terminating...
Jan 23 11:57:57 louis-GA401IU systemd[1]: Stopping key remapping daemon...
Jan 23 11:57:57 louis-GA401IU systemd[1]: keyd.service: Main process exited, code=exited, status=15/n/a
Jan 23 11:57:57 louis-GA401IU systemd[1]: keyd.service: Failed with result 'exit-code'.
Jan 23 11:57:57 louis-GA401IU systemd[1]: Stopped key remapping daemon.
Jan 23 11:57:57 louis-GA401IU systemd[1]: Started key remapping daemon.
Jan 23 11:57:57 louis-GA401IU keyd[12632]: Starting keyd v2.2.4-beta (d475661f9361fa24f166c9b5ed0b660b96a055b3).
Jan 23 11:57:57 louis-GA401IU keyd[12632]: Parsing /etc/keyd/default.conf
Jan 23 11:57:57 louis-GA401IU keyd[12632]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)
Jan 23 11:57:57 louis-GA401IU keyd[12632]: Managing Asus Keyboard (0b05:1866) (/etc/keyd/default.conf)```

I'm now more confused than I was yesterday.

**Comment by rvaiya** [comment] 2022-01-24 00:40
Hmm, I can't seem to reproduce this under Gnome either. Does this happen with any other bindings or just the `R'` macro? I can't see why adding `<' down> <' up>` to the sequence would cause 'R' to fail to be capitalized unless it was a time based issue (which is unlikely). Does adding a timeout (e.g `macro(R 200ms ')` help?

**Comment by Louis-dM** [comment] 2022-01-25 14:57
I think you're right, it's a time based thing. Adding the timeout helps. I can go as low as 4ms and it still works consistently, and that isn't noticable at all. Thank you!

***

A weird observation: you know how in a previous comment I said it was only working in Kitty and no other program? Well... I've also just discovered if I stop Kitty being fullscreen, it stops working again and only gives `r'`. And even if I then change it back to fullscreen, it won't give me `R'` until I restart keyd.

To be honest, I'm starting to wonder if it's a hardware thing. I've heard of people having problems with other distros on this laptop model, and although Fedora is supposed to be one of the few distros that work properly, it might just be that there are some problems with it too.

**Comment by rvaiya** [comment] 2022-01-25 18:39
> A weird observation: you know how in a previous comment I said it was only working in Kitty and no other program? Well... I've also just discovered if I stop Kitty being fullscreen, it stops working again and only gives r'. And even if I then change it back to fullscreen, it won't give me R' until I restart keyd.

That is indeed quite odd. Are you using `keyd-application-mapper`?

> To be honest, I'm starting to wonder if it's a hardware thing.

If adding a timeout to the macro helps then this is unlikely. Assuming keyd is (consistently) generating the appropriate codes as suggested by the output of `keyd -m` then a hardware issue can probably be ruled out, unless libinput is doing something weird to compensate for your device and the keyd virtual device is collateral (unlikely). 

More likely is that something in your input stack is doing time based things to disambiguate synthetic events from real ones, though I can't imagine what would cause `<leftshift down> <r down> <r up> <leftshift up> <' down> <' up>` to generate  `<r down> <r up> <' down> <' up>` instead (and I can't seem to reproduce it).

Can you run the following while reproducing the issue?

	sudo stdbuf -o0 libinput debug-events  --show-keycodes|tee libinput.log

It would help rule out problems between keyd and libinput.

**Comment by Louis-dM** [comment] 2022-01-25 23:55
> That is indeed quite odd. Are you using keyd-application-mapper?

Nope. Haven't tried it yet.

> Can you run the following while reproducing the issue?

> ```sudo stdbuf -o0 libinput debug-events  --show-keycodes|tee libinput.log```

```
-event3   DEVICE_ADDED            Power Button                      seat0 default group1  cap:k
-event9   DEVICE_ADDED            Asus Wireless Radio Control       seat0 default group2  cap:k
-event4   DEVICE_ADDED            Video Bus                         seat0 default group3  cap:k
-event0   DEVICE_ADDED            Lid Switch                        seat0 default group4  cap:S
-event1   DEVICE_ADDED            Power Button                      seat0 default group5  cap:k
-event2   DEVICE_ADDED            Sleep Button                      seat0 default group6  cap:k
-event6   DEVICE_ADDED            Logitech B330/M330/M3             seat0 default group7  cap:kp left scroll-nat scroll-button
-event5   DEVICE_ADDED            Asus Keyboard                     seat0 default group8  cap:k
-event7   DEVICE_ADDED            Asus Keyboard                     seat0 default group8  cap:k
-event8   DEVICE_ADDED            Asus Keyboard                     seat0 default group8  cap:kp scroll-nat
-event11  DEVICE_ADDED            ELAN1201:00 04F3:3098 Mouse       seat0 default group9  cap:p left scroll-nat scroll-button
-event13  DEVICE_ADDED            ELAN1201:00 04F3:3098 Touchpad    seat0 default group9  cap:pg  size 103x59mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on
-event12  DEVICE_ADDED            Asus WMI hotkeys                  seat0 default group10 cap:k
-event15  DEVICE_ADDED            keyd virtual keyboard             seat0 default group11 cap:kp left scroll-nat scroll-button
 event15  KEYBOARD_KEY            +4294967.295s	KEY_LEFTALT (56) pressed
 event15  KEYBOARD_KEY            +0.006s	KEY_TAB (15) pressed
 event15  KEYBOARD_KEY            +0.100s	KEY_TAB (15) released
 event15  KEYBOARD_KEY            +0.101s	KEY_LEFTALT (56) released
 event15  KEYBOARD_KEY            +1.939s	KEY_I (23) pressed
 event15  KEYBOARD_KEY            +2.099s	KEY_I (23) released
 event15  KEYBOARD_KEY            +2.644s	KEY_LEFTSHIFT (42) pressed
 event15  KEYBOARD_KEY            +2.644s	KEY_R (19) pressed
 event15  KEYBOARD_KEY            +2.644s	KEY_R (19) released
 event15  KEYBOARD_KEY            +2.644s	KEY_LEFTSHIFT (42) released
 event15  KEYBOARD_KEY            +2.644s	KEY_APOSTROPHE (40) pressed
 event15  KEYBOARD_KEY            +2.644s	KEY_APOSTROPHE (40) released
 event15  KEYBOARD_KEY            +7.857s	KEY_LEFTALT (56) pressed
 event15  KEYBOARD_KEY            +7.893s	KEY_TAB (15) pressed
 event15  KEYBOARD_KEY            +7.972s	KEY_LEFTALT (56) released
 event15  KEYBOARD_KEY            +7.997s	KEY_TAB (15) released
 event15  KEYBOARD_KEY            +9.098s	KEY_LEFTCTRL (29) pressed
 event15  KEYBOARD_KEY            +9.179s	KEY_C (46) pressed
```

I alt-tabbed to a different window where I knew would appear as `r'` just to be sure. `k` is pressed at +2.644s. The `keyd -m` log, running at the same time, shows the same order of keys being pressed and released.

**Comment by rvaiya** [comment] 2022-01-26 00:41
Thanks :).

If libinput is yielding the correct sequences then that only leaves the compositor. My version of gnome doesn't seem to do this, so it is possible that it has been patched in newer versions.

I am going to close this for now since it doesn't seem to be a keyd bug and can be worked around by adding additional timeouts. Do let me know if you find a way to reliably reproduce it or confirm the root cause.

P.S

Your rightshift woes can now be solved with `rightshift = rightshift`.

**Closed by rvaiya** 2022-01-26 00:41 UTC

**Comment by Louis-dM** [comment] 2022-01-26 19:03
Yup, I'll let you know if I ever figure out the cause.

Thanks for all the help!
