### ISSUE TITLE
Unrecognized EV_ABS code spammed to log when using touchpad

### ISSUE THREAD

**Issue by luveti** [rvaiya/keyd#380] opened 2022-11-14 21:39 UTC
On the latest commit (c597fd557f8399a46900476b8f0cc9f216313caa), the following gets printed to the log continuously when using the touchpad.

```
Nov 14 16:32:50 thinkpad keyd[529]: Unrecognized EV_ABS code: 24
Nov 14 16:32:50 thinkpad keyd[529]: Unrecognized EV_ABS code: 58
Nov 14 16:32:50 thinkpad keyd[529]: Unrecognized EV_ABS code: 24
Nov 14 16:32:50 thinkpad keyd[529]: Unrecognized EV_ABS code: 58
Nov 14 16:32:50 thinkpad keyd[529]: Unrecognized EV_ABS code: 24
Nov 14 16:32:50 thinkpad keyd[529]: Unrecognized EV_ABS code: 57
Nov 14 16:32:50 thinkpad keyd[529]: Unrecognized EV_ABS code: 24
```

This happens with or without config files. My trackpad is the following model `04f3:0076 Elan Touchpad`.

**Comment by rvaiya** [comment] 2022-11-19 03:25
Have you intentionally added your trackpad to the `[ids]` section? If not, you will probably want to exclude it using `-04f3:0076`, otherwise all mouse events will get routed through keyd (which currently has incomplete mouse support).

**Comment by tasnad** [comment] 2022-11-25 09:12
Hi,
I have the same issue:
```
Nov 25 10:01:25 user keyd[108764]: Unrecognized EV_ABS code: 24
Nov 25 10:01:25 user keyd[108764]: Unrecognized EV_ABS code: 47
Nov 25 10:01:25 user keyd[108764]: Unrecognized EV_ABS code: 53
Nov 25 10:01:25 user keyd[108764]: Unrecognized EV_ABS code: 54
Nov 25 10:01:25 user keyd[108764]: Unrecognized EV_ABS code: 47
Nov 25 10:01:25 user keyd[108764]: Unrecognized EV_ABS code: 53
Nov 25 10:01:25 user keyd[108764]: Unrecognized EV_ABS code: 54
```

I excluded the touchpad
```
[ids]
*
-0002:0007
```
but the logs are still there. (Just to mention it, I of course did restart keyd in between :))

I also tried with only adding the keyboard:
```
[ids]
0001:0001
```
but nothing changed.


This is how I found out which IDs my stuff has:
```
root@host # keyd monitor
[...]
device added: 0002:0007 SynPS/2 Synaptics TouchPad (/dev/input/event9)
[...]
```
Is this correct?

Just a side note: It would be nice to mention somewhere in the documentation how to find these IDs (e.g. with keyd monitor). I tried before with lsusb and lspci but did not succeed.

**Comment by ItsNilDev** [comment] 2022-11-26 14:42
same here

**Comment by rvaiya** [comment] 2022-11-26 23:34
Sorry, it appears this was indeed reporting for all devices. The output can be safely ignored. It should be gone in the latest commit.

**Comment by ItsNilDev** [comment] 2022-11-27 11:13
Thanks for the response, rvaiya

**Comment by rvaiya** [comment] 2022-11-28 07:30
I'm closing this for now. Feel free to reopen it if you feel the issue is unresolved.

**Closed by rvaiya** 2022-11-28 07:30 UTC
Labels: mouse

**Comment by kuadrat** [comment] 2024-02-19 07:39
Thank you for your work on `keyd`!

I still observe this issue on keyd version `2.4.3` (5e4ef41).

`/etc/keyd/default.conf`:
```
[ids]

*
-04f3:3193
-0002:000a
```

Some output of `keyd monitor` when tapping and clicking the touchpad:
```
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       rightmouse up
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       kpminus down
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       numlock down
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       kpminus up
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       numlock up
TPPS/2 Elan TrackPoint  0002:000a       leftmouse down
TPPS/2 Elan TrackPoint  0002:000a       leftmouse up
TPPS/2 Elan TrackPoint  0002:000a       middlemouse down
TPPS/2 Elan TrackPoint  0002:000a       middlemouse up
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       middlemouse up
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       middlemouse up
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       middlemouse up
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       kpminus down
ELAN0674:00 04F3:3193 Touchpad  04f3:3193       numlock down
```

`/var/log/syslog/` after `keyd reload` and then using the touchpad:
```
2024-02-19T08:36:11.444901+01:00 thinkpad keyd[713]: CONFIG: parsing /etc/keyd/default.conf
2024-02-19T08:36:11.444969+01:00 thinkpad keyd[713]: DEVICE: #033[31;1mignoring#033[0m 0fac:1ade  (keyd virtual pointer)
2024-02-19T08:36:11.445006+01:00 thinkpad keyd[713]: DEVICE: #033[31;1mignoring#033[0m 04f3:3193  (ELAN0674:00 04F3:3193 Touchpad)
2024-02-19T08:36:11.445017+01:00 thinkpad keyd[713]: DEVICE: #033[31;1mignoring#033[0m 04f3:3193  (ELAN0674:00 04F3:3193 Mouse)
2024-02-19T08:36:11.445025+01:00 thinkpad keyd[713]: DEVICE: #033[31;1mignoring#033[0m 056a:5289  (Wacom HID 5289 Finger)
2024-02-19T08:36:11.445034+01:00 thinkpad keyd[713]: DEVICE: #033[31;1mignoring#033[0m 056a:5289  (Wacom HID 5289 Pen)
2024-02-19T08:36:11.445046+01:00 thinkpad keyd[713]: DEVICE: #033[31;1mignoring#033[0m 0002:000a  (TPPS/2 Elan TrackPoint)
2024-02-19T08:36:11.445055+01:00 thinkpad keyd[713]: DEVICE: #033[32;1mmatch   #033[0m 0001:0001  /etc/keyd/default.conf#011(AT Translated Set 2 keyboard)
[...]
2024-02-19T08:37:29.900493+01:00 thinkpad keyd[713]: Unrecognized EV_ABS code: 53
2024-02-19T08:37:29.900571+01:00 thinkpad keyd[713]: Unrecognized EV_ABS code: 54
2024-02-19T08:37:29.907558+01:00 thinkpad keyd[713]: Unrecognized EV_ABS code: 53
2024-02-19T08:37:29.907636+01:00 thinkpad keyd[713]: Unrecognized EV_ABS code: 54
2024-02-19T08:37:29.928575+01:00 thinkpad keyd[713]: Unrecognized EV_ABS code: 57
```
