### ISSUE TITLE
enhanced oneshot action

### ISSUE THREAD

**Issue by newfix** [rvaiya/keyd#199] opened 2022-04-28 19:09 UTC
Hello!

First of all I would like to thank you for this awesome piece of software. It is exactly what I have been searching for. I am using it for different tasks and it works just fine.

Recently, I tried to configure something (that I will describe below) but could not find out how to do it with the existing actions. Therefore, I extended it (after all it's FOSS :-)) by implementing a further version of oneshot (which I called oneshot2).

I thought that this extension might be useful for other users as well. Therefore, I would be happy to contribute it.

What I was trying to achieve is the following:

`<press-shift> <press-a> <release-a> <release-shift> = A` 
(i.e. the normal behavior)

`<press-shift> <release-shift> <press-a> <release-a> <press-a> <release-a> = ba` 

In other words, I wanted to have a oneshot type of behavior, wherein pressing and releasing shift( (without any intermediate keyboard event) would activate a layer (just for the next event) in which 'a' is mapped to 'b' (which is what the current oneshot implementation supports), however without activating said layer while holding shift (which is not supported by the current implementation of oneshot).

The oneshot2 action I implemented is a "superset" of the existing oneshot action (i.e. it can be used as a drop-in replacement). Instead of having just one parameter (a layer) as is the case with oneshot, oneshot2 can be configured with 1, 2, or 3 parameters. The first parameter is the name of a layer that will be activated when holding the key. The second parameter is the name of a layer that will be activated when tapping the key (i.e. pressing it and releasing it without any intermediate keyboard event). The third parameter controls what happens when consecutively tapping the key several times.

The following descriptors are all equivalent:
```
x = oneshot(layerX)

x = oneshot2(layerX)

x = oneshot2(layerX, layerX)
```

So if only one layer is specified then it is activated when holding the key and when tapping it.

To achieve the behavior I described above the following configuration can be used:
```
[ids]
*

[main]
shift = oneshot2(shift, shiftlatched, cancel)

[shiftlatched]
a = b
```

If the third parameter is set to 'cancel' then tapping the key a second time will deactivate the "latched" layer (i.e. in the example above repeatedly tapping the shift key will toggle the activation state of the 'shiftlatched' layer).

If the third parameter is not set (or set to a value different from 'cancel') then consecutively tapping the key several times will not disable the "latched" layer (which corresponds to the behavior of the current implementation).

Please let me know whether I should send you the code. The easiest way for me would be to provide you a patch file that can be applied to the existing code base, so that you can review it and try it out.

**Comment by slakkenhuis** [comment] 2022-04-28 22:21
I can see that this may be useful and it's actually close to a feature that I was going to ask about (once I was more confident that it was a Good Idea), which is to allow not just macros, but also actions like `layer()`, `oneshot()` and `toggle()` as the second argument of `overload()`. I do think that that approach would be preferable to your `oneshot2()` operator, because it is clearer and doesn't introduce extra operators. Your example would become:

    [ids]
    *

    [main]
    shift = overload(shift, layer(shiftlatched))

    [shiftlatched]
    a = b
    shift = layer(main)

Another example use case would be to be able to do `shift = timeout(oneshot(shift), 800, overload(shift, layer(shift))`.

**Comment by rvaiya** [comment] 2022-04-29 02:12
```
What I was trying to achieve is the following:

<press-shift> <press-a> <release-a> <release-shift> = A (i.e. the normal behavior)

<press-shift> <release-shift> <press-a> <release-a> <press-a> <release-a> = ba
```

Can you provide a real world example of when this would be useful? I can't think of an instance in which it would be desirable to have:

```
<shift down>
<a down>
<shift up>
<a up>
```

and

```
<shift down>
<shift up>
<a down>
<a up>
```

produce two different outputs. 


The main problem is that it is easy to conflate:

```
<a down>
<b down>
<a up>
```

and

```
<a down>
<a up>
<b down>
```

in practice. This isn't an issue in the case of letters or overloaded modifiers, *provided they do the same thing in both cases*. 

However, having :

```
<shift down>
<shift up>
<b down>
```

and 

```
<shift down>
<b down>
<shift up>
```

do different things seems like a recipe for confusion. 

The best way to disambiguate these cases is with time (and even that is fraught), which can already be achieved using `timeout()`.

As @slakkenhuis observed, I would be more inclined to implement this as an extension of overload, though I remain unconvinced it is useful in practice.

**Comment by slakkenhuis** [comment] 2022-04-29 12:10
> This is different from the intended oneshot type behavior, which produces '**ba**' as described above.

Oh, I didn't realize that you wanted to essentially have a oneshot key that... oneshots a different layer on tap. I would amend my example to:

    ....
    shift = overload(shift, oneshot(shiftlatched))

    [shiftlatched]
    a = b
    shift = noop

> how it could help me to cover my use case.

It doesn't, it's just another case that would benefit from the flexibility. It's like a oneshot layer for shift but additionally locks the layer if you hold the tap for some length of time. While I have wanted to do that, I didn't feel yet that it's important enough to warrant inclusion, so it's just been in the back of my head in case I encounter other use cases (like yours now)

> I am not suggesting to introduce an additional operator

Ah, I misunderstood. Got it!

**Comment by slakkenhuis** [comment] 2022-04-29 18:16
>I am not sure why you think it would make me "crazy". 
Haha, I don't think it makes you crazy --- I have tried overloading space too! --- I'd think it'd make you *go* crazy. 

>this might of course be different depending on the way you type.
Indeed. For me, the wrong action is triggered multiple times in a sentence if I do that. I'm surprised and mildly impressed that it doesn't for you. Different strokes!

As for the issue at hand, I just remembered that I also at one point wanted to do this:

```
control = overload(control, oneshot(function))

[function]
a = f1
s = f2
...
```

... which is very similar to what you're trying to achieve. I'm not sure that it'd be ergonomical, but I thought I'd mention it as another use case.

**Comment by rvaiya** [comment] 2022-05-01 06:40
> I agree that when considering two arbitrary keys which are consecutively pressed we cannot be sure about the order of the `up` and `down` events
> However, in case the first key is a modifier (e.g. `shift`) the situation is different IMHO. 
>
> ....
>
> We just need to assume that:
>
> (1) the modifier key is pressed first (because otherwise it would not produce
> the desired effect in the first place);
>
> (2) the modifier key is not released before the other key has been pressed.

1 is a reasonable assumption, but I suspect you will find 2 be more of a problem than you initially suppose. In the course of normal typing it is actually quite difficult to intentionally distinguish between `<a down> <b down> <a up>` and `<a down> <a up> <b down>` without sacrificing speed or changing your typing habits. This is one of the reasons many people struggle with home row mods (which usually involve timeouts).

> However, at least for me the risk of releasing `shift` before pressing the key for a letter
> that I want to type in uppercase is neglectable and is by far outweighed by the
> usefulness of the use case described above.

The problem you are more likely to encounter is that you will end up accidentally upper casing something when you mean to activate one of your shortcuts.

I.E

```
<shift down>
<a down>
<shift up>
```

(S-a)

when you meant

```
<shift down>
<shift up>
<a down>
```

(C-c)

>  I have tried overloading space too! --- I just think it'd make you go crazy.

+1

Having said that, making overload more flexible seems like a reasonable compromise and also facilitates a few other use cases.

**Comment by rvaiya** [comment] 2022-05-03 21:17
> Believe it or not, I am not just hypothesizing that the two features I
> described above (i.e. using the space key as a modifier and using an overloaded
> shift key to trigger oneshot actions) could potentially be of some use. 

I am glad to hear it, though I am surprised the overloaded space doesn't bother you.

> No, they are actually the single most used shortcuts in my daily work on a
keyboard since years :-)

Different strokes (pun intended) for different folks ;).

> I just wanted to point out that the first feature can be nicely configured
> using keyd and that I have enhanced the current implementation of oneshot to
> support the second feature. However, I am not trying to convince anyone to use
> those features. My goal was rather to share my experience and to offer a small
> contribution regarding an enhanced oneshot operator that I am currently using.

Thanks for taking the time to experiement and create this issue. keyd favours a composable approach, but the thrust of your idea is sound.

> If you think that there are no other users who could benefit from sharing any
> of the mentioned features or from other uses of the enhanced oneshot operator
> (or that it is maybe even "too risky" to give them the choice) then that's fine
> with me of course. 

My goal is not to protect the user from themselves so much as is it to avoid cluttering the code features which are unusable in practice.  Your personal experience is a reasonable consideration in this regard.

I've modifier overload so it accepts an arbitrary action. It should be possible to achieve what you want like so:

```
[main]

shift = overload(shift, oneshot(control))

[control]

shift = noop
```

**Comment by rvaiya** [comment] 2022-05-05 18:19
I'm closing this for now, feel free to reopen if you feel the issue is unresolved.

**Closed by rvaiya** 2022-05-05 18:19 UTC
Labels: enhancement, implemented, overloading
