### ISSUE TITLE
Fails on startup but works fine on restart

### ISSUE THREAD

**Issue by adast9** [rvaiya/keyd#122] opened 2022-01-30 16:16 UTC
My [config](https://raw.githubusercontent.com/adamstuck/dotfiles/main/.config/keyd/default.conf)

Startup:

> Jan 30 17:03:35 ooz systemd[1]: Started key remapping daemon.
Jan 30 17:03:35 ooz keyd[578]: Starting keyd v2.2.4-beta (0dd39a3606807fb50ec0e11bda31c84f586a3a96).
Jan 30 17:03:35 ooz keyd[578]: Parsing /etc/keyd/default.conf
Jan 30 17:03:36 ooz keyd[578]: open: No such device
Jan 30 17:03:36 ooz keyd[578]: cleaning up and terminating...
Jan 30 17:03:36 ooz systemd[1]: keyd.service: Main process exited, code=exited, status=255/EXCEPTION
Jan 30 17:03:36 ooz systemd[1]: keyd.service: Failed with result 'exit-code'.

On restart:

> Jan 30 17:04:59 ooz systemd[1]: Started key remapping daemon.
Jan 30 17:04:59 ooz keyd[1049]: Starting keyd v2.2.4-beta (0dd39a3606807fb50ec0e11bda31c84f586a3a96).
Jan 30 17:04:59 ooz keyd[1049]: Parsing /etc/keyd/default.conf
Jan 30 17:05:01 ooz keyd[1049]: Managing SEMITEK USB-HID Gaming Keyboard (1ea7:0907) (/etc/keyd/default.conf)
Jan 30 17:05:01 ooz keyd[1049]: Managing SEMITEK USB-HID Gaming Keyboard (1ea7:0907) (/etc/keyd/default.conf)
Jan 30 17:05:01 ooz keyd[1049]: No config found for Logitech G Pro  (046d:4079)

**Comment by rvaiya** [comment] 2022-01-30 18:43
This is presumably because `/etc/` is not available before systemd tries to start the unit on your system. Are you using something like full disk encryption? What distro are you running?

**Comment by adamstuck** [comment] 2022-01-30 19:28
I'm using no form of encryption and I'm on Arch.
Btw, I have been using keyd without this issue for weeks so this is pretty new.

**Comment by rvaiya** [comment] 2022-01-31 08:34
Sorry, I should have scrutinized your log more carefully. The issue seems to be related to attempts to prematurely grab the input devices.

I will try and reproduce this when I get some time, though I am currently working on some related plumbing which might indirectly solve this problem.

**Comment by adamstuck** [comment] 2022-02-01 12:01
I am not sure if this helps or not but I found a workaround that doesn't require restarting the service.
If I plug in my keyboard once I have reached the tty login screen, keyd works as usual. (I can login with colemak)
It seems like I can unplug the keyboard at any point before login and this method still works.

**Comment by rvaiya** [comment] 2022-02-03 01:55
Thanks for the detailed follow-up. I wasn't able to reproduce this, but what you describe is consistent with my original hypothesis. I've changed the way hotplug detection works in the latest commit which should make it a little more robust. Can you give the latest version a try and see if you can reproduce the issue?

**Comment by adast9** [comment] 2022-02-03 02:13
The update seems to have helped with grabbing the keyboard when booting from shutdown but keyd still fails to load (same error) on system reboot.

**Comment by rvaiya** [comment] 2022-02-03 03:04
Hmm, I've added some additional logging. Can you give it another try?

**Comment by adast9** [comment] 2022-02-03 10:48
Here's the log:

**Comment by rvaiya** [comment] 2022-02-03 20:30
It looks like there a race condition between device detection and the grab attempt. It seems the system is removing the evdev node before keyd attempts to grab it (presumably because the hardware is doing weird things). The latest patch should treat these errors as non fatal. Give it another go.

**Comment by adast9** [comment] 2022-02-03 22:08
I just did a bunch of shutdown -> power on and also reboots and the issue seems fixed completely.

> Feb 03 23:05:05 ooz systemd[1]: Started key remapping daemon.
Feb 03 23:05:05 ooz keyd[645]: Starting keyd v2.2.5-beta (510a428360f8fd1e1b3d45c20729f2e3b8393d6b).
Feb 03 23:05:05 ooz keyd[645]: Parsing /etc/keyd/default.conf
Feb 03 23:05:05 ooz keyd[645]: is_keyboard: Failed to open /dev/input/event6
Feb 03 23:05:06 ooz keyd[645]: Managing SEMITEK USB-HID Gaming Keyboard (1ea7:0907) (/etc/keyd/default.conf)
Feb 03 23:05:06 ooz keyd[645]: Managing SEMITEK USB-HID Gaming Keyboard (1ea7:0907) (/etc/keyd/default.conf)
Feb 03 23:05:24 ooz keyd[1158]: No config found for Logitech G Pro  (046d:4079)

Here's the log. Sometimes there is no is_keyboard error. Sometimes the Logitech G Pro message isn't there.

**Comment by rvaiya** [comment] 2022-02-04 03:54
Thanks

**Comment by rvaiya** [comment] 2022-03-21 20:22
Can you try the latest version?

**Comment by adast9** [comment] 2022-03-22 21:37
Hey, I wasn't even aware that there was a new version. Seems like I had to force the AUR download.
Anyway I found some time to try out v2.3.0 and migrate my [config](https://github.com/adast9/dotfiles/commit/9a5f5448bd2407594eed751f87a83d4876917e89?diff=unified).

It seems like the issue on startup is fixed. I haven't experienced it since updating.
Also the composite layers work great 😄. Definitely feels more intuitive.

The only thing I was a little confused about was the fact that I had to explicitly setup my qwerty layout now, by "resetting" the key maps. You can see what I mean in the link. Is there any way around this?

**Comment by rvaiya** [comment] 2022-03-23 03:24
> The only thing I was a little confused about was the fact that I had to
> explicitly setup my qwerty layout now, by "resetting" the key maps. You can
> see what I mean in the link. Is there any way around this?

I would do something like this

	[main]

	capslock = layer(capslock)

	[colemak]

	a = a
	s = r
	...

	[capslock:C]

	1 = toggle(colemak)

If you want to avoid the additional keystroke, then what you have done is the correct
way to achieve it.

> Another thing: can composites not inherit from modifier sequences?

No. The modifier set will always be the combined modifiers of the constitutent
layers. So `[control+shift]` will always behave as 'C-S' for anything not
defined within it. It would be counterintuitive to redefine this behaviour, but
you are free to individually reassign keys within the layer (to which the
layer modifiers will not apply), 

E.G

	[control+shift]

	a = A-a
	b = A-b

I am not opposed to changing this behaviour if you can make a good case for it in a dedicated issue.

**Closed** 2022-03-23 08:51 UTC
Labels: bug, todo, heisenbug
