### ISSUE TITLE
Is it possible to have different config per device?

### ISSUE THREAD

**Issue by Sp1r7t** [rvaiya/keyd#265] opened 2022-07-23 16:17 UTC
Hi! First of all, thanks for your great work!

So, I have a gaming mouse with 12 side buttons and a regular keyboard. 
Currently I use keyd to remap only my mouse, and now I'd like to also remap my keyboard.

Is it possible to have one set of keybinds for one device and a different set of keybinds for other?

**Comment by slakkenhuis** [comment] 2022-07-23 16:39
[Yes](https://github.com/rvaiya/keyd/blob/99a786979612068d319cfdef95b560e46913e03e/docs/keyd.scdoc#L48) --- you can add multiple `.conf` files in `/etc/keyd/`, each with different `[ids]` sections.

**Comment by Sp1r7t** [comment] 2022-07-23 17:22
Thanks, that works. Now, when I use ~/.config/keyd/app.conf, is there any way to apply it only to one device?

**Comment by slakkenhuis** [comment] 2022-07-23 18:18
Yes: instead of `*` in the `[ids]` section, you would indicate the device IDs; see the manual entry. To find out the correct device IDs, use `lsusb` (or `keyd -m`).

As an aside, I don't think `~/.config/keyd/` works, since `keyd` only works on the system-level (unless something changed). `/etc/keyd` is the expected spot for configuration files.

**Comment by rvaiya** [comment] 2022-07-24 06:47
> As an aside, I don't think ~/.config/keyd/ works

He is asking about ` ~/.config/keyd/app.conf` which is part of the application remapping functionality. Unfortunately there is presently no way to configure application specific logic on a per device basis. See #264.

**Comment by rvaiya** [comment] 2022-08-03 07:01
Depending on what you are trying to achieve, this should now be possible using aliases. I assume your goal is to distinguish between otherwise identical keys emitted by your mouse and your keyboard. 

The trick is to bind a unique alias within your keyboard config and then use the unique name within your application bindings as described in #264. I am closing this for now, but feel free to reopen it if you feel the issue is unresolved.

**Closed** 2022-08-03 07:02 UTC
Labels: question, application mapping

**Comment by Sp1r7t** [comment] 2022-08-07 20:09
Not exactly.

Here's what I was trying to do:
1. Create a config for my mouse
2. Create a different config for my keyboard
3. Use application mapper to change keybinds on my mouse but not on my keyboard


Is it possible to make it work with aliases?


I guess something like this is `default.conf`:
```
[ids]

*

-0c45:8508

[aliases]
myButton1 = macro(C-w)
myButton2 = macro(C-t)
myButton3 = macro(C-S-t)
...
myButton12 = macro(C-S-p)

[main]

1 = mouse1
2 = mouse2
3 = mouse3
...
home = mouse12

```

and like this `app.conf`
```
[firefox]

myButton1 = f5
myButton2 = macro(C-S-v)
myButton3 = macro(M-d)
```

Would something like that work?

**Comment by rvaiya** [comment] 2022-08-07 22:11
There are several problems with that config. Aliases cannot be arbitrary values (please see the man page). If your mouse generated buttons, and not keys then you don't need to create a separate config or aliases. Just add your mouse id to the `[ids]` section of default and remap the buttons within app.conf. 

E.G

/etc/keyd/default.conf:
```
[ids]
*
<mouse id>
```

~/.config/keyd/app.conf
```
[firefox]
button1 = macro(C-S-v)
# etc...
```

**Comment by Sp1r7t** [comment] 2022-08-08 07:11
My mouse generates keys. By default, it's set to numbers.
I just thought with aliases I could have `myCustomButton = keybind`

Here's my current config in `default.conf`
```
[ids]

*

-0c45:8508

[main]

1 = macro(C-w)
2 = macro(C-t)
3 = macro(C-S-t)
4 = macro(C-S-tab)
5 = space
6 = macro(C-tab)
7 = home
8 = f5
9 = macro(C-S-v)
minus = macro(M-d)
end = macro(A-f4)
home = macro(C-S-p)
```

I grab all devices and exclude my keyboard, so it works when my mouse is plugged in via wireless dongle and wired.

In `app.conf` I have this:
```
[gw2-64-exe]
1 = kp1
2 = kp2
3 = kp3
4 = kp4
5 = kp5
6 = kp6
7 = kp7
8 = kp8
9 = kp9
minus = minus
end = rightbrace
home = kpdot
```

Currently, I use it only with my mouse, but I'd like to add another config for my keyboard:
```
[ids]

0c45:8508

[main]

capslock = kpdot
# and maybe few other keys...
```

**Comment by rvaiya** [comment] 2022-08-08 07:53
Then just assign the mouse buttons unique aliases in a dedicated config and use them in your app.conf.

E.G

```
[ids]
<mouse id>

[aliases]
kp1 = button1
kp2 = button2
# ...
```

app.conf:
```
[firefox]
button1 = f1
# etc...
```

**Comment by Sp1r7t** [comment] 2022-08-08 13:10
I tried that.

```
[ids]

1532:0090

[aliases]
1 = button1
2 = button2
# ...
home = button12
```

And this in in `app.conf`
```
[firefox]

button4 = q
button5 = w
button6 = e

[brave-browser]

button4 = z
button5 = x
button6 = c
```

It works fine until I add config for my keyboard. Then, I get "ERROR: button4 is not a valid keycode or alias."

```
[ids]

0c45:8508

[main]
capslock = kpdot
```

**Comment by rvaiya** [comment] 2022-08-10 03:32
Sorry, you're right. That doesn't work because keyd's client only operates on the most recently active device by default. I have modified this behaviour in the latest commit. Can you try the same config using the latest commit?

**Comment by Sp1r7t** [comment] 2022-08-10 06:18
I just tried it and it works. Thank you!
