### ISSUE TITLE
Bug: Segfault on reload when id section changes

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#344] opened 2022-09-19 21:44 UTC
For testing, I managed two keyboards with separate configuration files, the id sections of the files were
```
[ids]
*
-0001:0001
```
and
```
[ids]
0001:0001
```
When testing was finished, I commented out both lines with the specific keyboard id and triggered a reload, but keyd only picked up the other keyboard and then segfaulted after a while. When starting again, both keyboards were picked up correctly.

As a side note: `reload` is missing in the command section of the manual.

**Comment by rvaiya** [comment] 2022-09-20 06:58
I haven't been able to reproduce this. It's worth noting that you don't need `-0001:0001` in your first config as keyd will automatically select the config with the most specific match.

>  but keyd only picked up the other keyboard
 
Can you post the log output?

**Comment by rvaiya** [comment] 2022-09-20 20:52
Can you post the full log (after restart)?

**Comment by rvaiya** [comment] 2022-09-21 00:58
Thanks for the detailed reproduction steps. Can you try the latest commit? I believe this should be fixed.

**Comment by rvaiya** [comment] 2022-09-21 20:34
Odd, this should work. Did you install it, or are you running it in the source directory? If you aren't using the same client and server version it can wreak havoc (avoid `keyd reload` if you are running `./bin/keyd`). 

Can you post the full log output when reproducing this? If keyd is actually unresponsive (the panic sequence doesn't work) you should be able to just unplug and replug your keyboard since it won't be able to grab the device.

**Comment by rvaiya** [comment] 2022-09-22 07:37
oops. It looks like I forgot to skip the virtual keyboard on reload. I hadn't noticed since I had explicitly excluded it from test my configs. Thanks for the log output. I believe this should be fixed.

**Closed as completed** 2022-09-22 08:39 UTC
Labels: heisenbug
