### ISSUE TITLE
Unicode Macros do not seem to work

### ISSUE THREAD

**Issue by kanjiTreeGirl** [rvaiya/keyd#736] opened 2024-05-02 05:27 UTC
I have followed the guide on enabling unicode for keyd, and thought the following would work
```
[ids]
*
[main]
capslock = layer(test)
[test:capslock]
j= 𛁪 
o+p = ~
l = macro(compose o ")
```
o+p and l work as expected, but whenever I am holding down j all I get is kt8,

The following is my sudo keyd monitor output.

```
keyd virtual keyboard	0fac:0ade	cancel down
keyd virtual keyboard	0fac:0ade	cancel up
keyd virtual keyboard	0fac:0ade	k down
keyd virtual keyboard	0fac:0ade	k up
keyd virtual keyboard	0fac:0ade	t down
keyd virtual keyboard	0fac:0ade	t up
keyd virtual keyboard	0fac:0ade	8 down
keyd virtual keyboard	0fac:0ade	8 up
```

And, as expected, the following is in my /usr/share/X11/locale/keyd.compose file
`<Cancel> <k> <t> <8> : "𛁪"`

Thank you in advance

**Comment by nsbgn** [comment] 2024-05-02 08:55
This works for me. Are you on Wayland? Does it work if you symlink `~/.XCompose` to the provided `keyd.compose` file? 

As an aside, I don't think `[test:capslock]` is a valid layer name, at least not in the current version of keyd --- `capslock` is not a modifier.

**Comment by nsbgn** [comment] 2024-05-03 16:10
Hmm, I can't reproduce this. The emitted keys are correct...

See if you can figure out which Compose file is selected and if that one really has the `<Cancel> <k> <t> <8> : "𛁪"` line in it. Like, are the permissions on the Compose file wrong? Is your `$XCOMPOSEFILE` set? See <https://www.x.org/releases/current/doc/man/man5/Compose.5.xhtml>

**Comment by kanjiTreeGirl** [comment] 2024-05-04 04:25
Updated eerything and reinstalled, set my ComposeFile and now everything works.
Thanks!

**Comment by rvaiya** [comment] 2024-05-04 05:55
Closing, since this has been answered by the indefatigable slakkenhuis ;).

**Closed by rvaiya** 2024-05-04 05:55 UTC
