### ISSUE TITLE
Using layer with modifier Alt works wrong in some programs

### ISSUE THREAD

**Issue by antontkv** [rvaiya/keyd#128] opened 2022-02-07 03:53 UTC
Hello.

Some programs, like for example Firefox, treat taping Alt as toggle for showing the menu. So if you have config like this:
```
[main]
leftalt = layer(alt)

[alt]
h = left
j = down
k = up
l = right
```
There will be a conflict with that menu. This is because when you hit `A-j` to activate `Down` key, the program does this:

- Release Left Alt
- Press Down
- Release Down
- Press Left Alt

So when you press Alt and then keyd releases Alt, Firefox treats this as taping Alt and shows the menu.

If we take AutoHotKey and look how they do Alt releases, then we see this:
```
KeyPress event, serial 30, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 1295265, (50,858), root:(238,1069),
    state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 1295718, (50,858), root:(238,1069),
    state 0x8, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 1295734, (50,858), root:(238,1069),
    state 0xc, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 1295750, (50,858), root:(238,1069),
    state 0x8, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 1295765, (50,858), root:(238,1069),
    state 0x0, keycode 104 (keysym 0xff54, Down), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 1295781, (50,858), root:(238,1069),
    state 0x0, keycode 104 (keysym 0xff54, Down), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 1295796, (50,858), root:(238,1069),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 1295812, (50,858), root:(238,1069),
    state 0x4, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 1295828, (50,858), root:(238,1069),
    state 0xc, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

So the order is this:

- You press Alt
- Then press j to trigger Down key

AHK does this:

- Press Left Ctrl
- Release Left Ctrl
- Release Left Alt
- Press Down
- Release Down
- Press Left Ctrl
- Press Left Alt
- Release Left Ctrl

Indeed if you go to Firefox, press Alt then tap Left Ctrl and then release Alt, the menu won't show up.

To try it out I changed `set_mods` functions in `src/keyd.c` to this: 
```c
void set_mods(uint16_t mods)
{
	static uint16_t state = 0;
	size_t i;

	uint16_t diff = mods ^ state;

	if (debug && diff)
		fprintf(stderr, "Active mods: %s\n", modstring(mods));

	if (MOD_CTRL & diff)
		send_key(KEY_LEFTCTRL, !!(MOD_CTRL & mods));
	if (MOD_ALT_GR & diff)
		send_key(KEY_RIGHTALT, !!(MOD_ALT_GR & mods));
	if (MOD_SHIFT & diff)
		send_key(KEY_LEFTSHIFT, !!(MOD_SHIFT & mods));
	if (MOD_SUPER & diff)
		send_key(KEY_LEFTMETA, !!(MOD_SUPER & mods));
	if (MOD_ALT & diff)
                if (!!(MOD_ALT & mods) == 0) {
                    send_key(KEY_LEFTCTRL, 1);
                    send_key(KEY_LEFTCTRL, 0);
		    send_key(KEY_LEFTALT, !!(MOD_ALT & mods));
                } else {
                    send_key(KEY_LEFTCTRL, 1);
                    send_key(KEY_LEFTALT, !!(MOD_ALT & mods));
                    send_key(KEY_LEFTCTRL, 0);
                }

	state = mods;
}
```

And it works without interfering with menu in Firefox. I don't know C to make any meaningful PR. With my hack Left Ctrl triggers on every Alt press, but should be only on pressing reconfigured keys like `j` and I don't know how to do this.

**Comment by rvaiya** [comment] 2022-02-07 04:26
What is your AHK config? My guess is that AHK doesn't support modifiers like keyd, in which case it doesn't emit alt as soon as alt is pressed. You can emulate this in keyd by defining a non modifier layer.

**Comment by antontkv** [comment] 2022-02-07 04:45
AHK config for this is:
```
!h:: Send {Left}
!l:: Send {Right}
!j:: Send {Down}
!k:: Send {Up}
```

AHK supports modifier keys and emit alt as soon as it pressed.

I want modifier layer. I want Alt to behave normal in most cases, and change it behavior in some.

Problem not in AHK, it with programs that use Alt as toggle for the menu. AHK just found a way to mitigate that, by pressing Ctrl, before releasing Alt.

**Comment by rvaiya** [comment] 2022-02-07 04:46
Can you show me the full config? What does AHK do when you press `alt+c`? Does it emit an extraneous control sequence in every case?

**Comment by rvaiya** [comment] 2022-02-07 04:48
P.S You can use `keyd -m` to monitor the output instead of xev.

**Comment by antontkv** [comment] 2022-02-07 04:56
> Can you show me the full config?

Sorry I can't show you all config. But I tested the this config with the same result:
```
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

!h:: Send {Left}
!l:: Send {Right}
!j:: Send {Down}
!k:: Send {Up}
```

> What does AHK do when you press alt+c? Does it emit an extraneous control sequence in every case?

No it don't. It only does it for `hjkl`, only for keys that I reconfigured.

```
KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 5925375, (410,854), root:(442,909),
    state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 5925796, (410,854), root:(442,909),
    state 0x8, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (63) "c"
    XmbLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 5925875, (410,854), root:(442,909),
    state 0x8, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 5926062, (410,854), root:(442,909),
    state 0x8, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

> P.S You can use keyd -m to monitor the output instead of xev.

Sorry, I don't have keyd installed on windows machine.

As I said I changed `set_mods` function and everything works fine, except it generate left Ctrl on every Alt press and it only need to do this for reconfigured keys.

**Comment by rvaiya** [comment] 2022-02-07 05:23
This seems like bad default behaviour since it is not safe to assume that the additional control will be ignored by all software. 

What happens if you do `<alt down> <j down> <j up> <c down> <c up> <alt up>`? How does AHK decide when to send the additional control sequences?

There is no way to achieve this in keyd at the moment (it might be possible by abusing macros and relying on some implementation details) since it does not expose the individual events by design.

You could do something like this:

```
[myalt]
a = A-a
b = A-b
...
j = down
...
```

to avoid this problem, but you won't be able to use alt on its own.

**Comment by antontkv** [comment] 2022-02-07 05:35
> This seems like bad default behaviour since it is not safe to assume that the additional control sequences will be ignored by all software.

Well it works =) And I never had problem with this.

> What happens if you do <alt down> <j down> <j up> <c down> <c up> <alt up>? How does AHK decide when to send the additional control sequences?

```
KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8293656, (662,678), root:(746,785),
    state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8293953, (662,678), root:(746,785),
    state 0x8, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8293968, (662,678), root:(746,785),
    state 0xc, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8293984, (662,678), root:(746,785),
    state 0x8, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8294000, (662,678), root:(746,785),
    state 0x0, keycode 104 (keysym 0xff54, Down), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8294015, (662,678), root:(746,785),
    state 0x0, keycode 104 (keysym 0xff54, Down), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8294031, (662,678), root:(746,785),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8294046, (662,678), root:(746,785),
    state 0x4, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8294062, (662,678), root:(746,785),
    state 0xc, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8294671, (662,678), root:(746,785),
    state 0x8, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (63) "c"
    XmbLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8294750, (662,678), root:(746,785),
    state 0x8, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x200001,
    root 0x36e, subw 0x0, time 8295234, (662,678), root:(746,785),
    state 0x8, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

If it helps I found explanation in AHK source code:

https://github.com/Lexikos/AutoHotkey_L/blob/5d5a569f123f68cbd522d90bf6780f2b3be404af/source/keyboard_mouse.cpp#L3125-L3130

https://github.com/Lexikos/AutoHotkey_L/blob/5d5a569f123f68cbd522d90bf6780f2b3be404af/source/keyboard_mouse.cpp#L3273-L3282

**Comment by rvaiya** [comment] 2022-02-07 05:58
Thanks for the references. It looks like you have found the war and peace of modifier state :P. I will need some time to digest it and think about all the implications.

**Comment by rvaiya** [comment] 2022-02-07 07:15
> It might be possible by abusing macros and relying on some implementation details

I thought it about it a bit more and realized that you can do:

```
j = macro(A-leftcontrol down A-leftcontrol)
k = macro(A-leftcontrol up A-leftcontrol)
...
```

This works because keyd takes a conservative approach to key events and won't emit the alt up event until it processes the first sequence which can make use of the current modifier state. Similarly it won't emit a dedicated alt down event at the end of the macro since the last key sequence already contains one. This is technically an implementation detail that is subject to change, but it should do exactly what.

**Comment by antontkv** [comment] 2022-02-07 08:25
This works. Thank you! =)
Migrated my configuration from AHK, and everything works as expected. 
Finally found keyboard remapper for Linux that works and not total pain to configure. =)

**Comment by rvaiya** [comment] 2022-02-17 21:40
This is now the default behaviour. Your config can simply become:

```
[main]
leftalt = layer(alt)

[alt]
h = left
j = down
k = up
l = right
```

The workaround I posted no longer works since the implementation detail it relied upon has changed.

**Comment by antontkv** [comment] 2022-02-20 08:25
Thank you. I tested new version and everything works as expected.

**Comment by rvaiya** [comment] 2022-02-20 18:47
Thanks for the confirmation :). I'm going to close this for now.

**Closed by rvaiya** 2022-02-20 18:47 UTC
