### ISSUE TITLE
How to map unsupported key?

### ISSUE THREAD

**Issue by Fisiu** [rvaiya/keyd#428] opened 2023-01-26 19:49 UTC
On of my key is visible as:
`ERROR: unsupported evdev code: 0x174`

How to map it to something useful using keyd?

**Comment by Fisiu** [comment] 2023-02-16 19:45
`evtest` for this particular key shows:
```log
Event: time 1676573287.288413, type 4 (EV_MSC), code 4 (MSC_SCAN), value 91
Event: time 1676573287.288413, type 1 (EV_KEY), code 372 (KEY_ZOOM), value 1
Event: time 1676573287.288413, -------------- SYN_REPORT ------------
```

I've added new file:
```sh
❯ cat /etc/udev/hwdb.d/70-keyboard.hwdb
# zoom key
evdev:atkbd:dmi:bvn*:bvr*:bd*:svn*:pn*:pvr*
 KEYBOARD_KEY_91=coffee
```

Then just applied changes using:
```
❯ sudo systemd-hwdb update
❯ sudo devadm trigger /dev/input/event0
```

Where `event0` is my keyboard.
Now `evtest` shows:
```
Event: time 1676576271.112215, type 4 (EV_MSC), code 4 (MSC_SCAN), value 91
Event: time 1676576271.112215, type 1 (EV_KEY), code 152 (KEY_SCREENLOCK), value 1
Event: time 1676576271.112215, -------------- SYN_REPORT ------------
```
And I can finally map this key to F11 or F4 (with meta):
```ini
[main]
coffee = f11

[meta]
coffee = f4
```

I'm still not sure if it's possible to map this key using keyd without remapping in udev first. Meanwhile, the above solution works for me.

**Comment by ignapk** [comment] 2023-02-24 05:13
I submitted a pull request to fix it here https://github.com/rvaiya/keyd/pull/449

**Comment by rvaiya** [comment] 2023-02-24 20:47
@Fisiu Sorry for neglecting this for so long. I put it on my TODO list and promptly forgot about it. Can you try the latest commit?

**Comment by ignapk** [comment] 2023-02-24 22:05
> @Fisiu Sorry for neglecting this for so long. I put it on my TODO list and promptly forgot about it. Can you try the latest commit?

the latest commit still doesn't work, because the 177 decimal code is equivalent to KEY_SCROLLUP and that's what the key is detected as after this commit; I have updated my PR to take into account changed name to alias (KEY_FULL_SCREEN vs KEY_ZOOM, which are the same currently but didn't use to be) and different internal code (which doesn't matter in this case)

**Comment by rvaiya** [comment] 2023-02-24 22:56
> the latest commit still doesn't work, because the 177 decimal code

177 is the internal keyd code, not the evdev key. There is no overlap. Do you actually have the hardware to test this? If not, I would prefer to wait for confirmation from the issue author. I believe db28a18 should make the key reassignable.

**Comment by ignapk** [comment] 2023-02-24 23:26
I do actually have the hardware to test this, and while https://github.com/rvaiya/keyd/commit/db28a18a6ed73675e30a568ee6bfe27b413f93b3 does make it possible to reassign it, it breaks its functionality without reassigning it - they key shows up as KEY_SCROLLUP in evtest instead of KEY_FULL_SCREEN

**Comment by rvaiya** [comment] 2023-02-24 23:35
>  it breaks its functionality without reassigning it.

Sorry, I forgot to add zoom as a valid output. This should be remedied by a48ff465.

**Comment by ignapk** [comment] 2023-02-24 23:39
I can confirm that adding https://github.com/rvaiya/keyd/commit/a48ff465e820891f3d3c96bc45e20baad2063129 fixes this issue :+1:

**Comment by rvaiya** [comment] 2023-02-24 23:55
Thanks for the confirmation. I'm closing this for now. @Fisiu feel free to reopen if the issue is unresolved.

**Closed by rvaiya** 2023-02-24 23:55 UTC
