### ISSUE TITLE
Press/release of modifier while key in layer held activates it's default modifier

### ISSUE THREAD

**Issue by i-c-u-p** [rvaiya/keyd#201] opened 2022-05-01 07:16 UTC
While holding <kbd>capslock</kbd> to activate the `CapsLayer` layer , if I hold a movement key [<kbd>jkl;</kbd>] then hold <kbd>d</kbd> to shift, it adds the <kbd>control</kbd> modifier which stays after letting go of <kbd>d</kbd> and until releasing and pressing the movement key again. for some reason doing it the other way around (holding <kbd>d</kbd> to shift and then a movement key) works as expected until <kbd>d</kbd> is released, then <kbd>control</kbd> is activated until the movement key is released & pressed again like before. Keyd version is d4b8194.

<details>
<summary>
/etc/keyd/default.conf:
</summary>

```
[ids]
*

[main]
capslock = layer(CapsLayer)

[CapsLayer:C]
j = left
k = down
l = up
; = right
space = layer(control)
d = layer(shift)
```

</details>

Here's a couple vids demonstrating the problem:

https://user-images.githubusercontent.com/96894903/166136104-ef2b7d86-f7d7-41aa-beb8-4fa3348bf55c.mp4

https://user-images.githubusercontent.com/96894903/166136111-ab30f3a4-caa9-4c62-ac0e-6443c7162298.mp4

The text on the right window is the output from this command: 

`sudo keyd -m | sed "s/$kbdId/<keyboard id>/g;s/$mouseId/<mouse id>/g;s/$kbdName/<keyboard name>/g;s/$mouseName/<mouse name>/g;"`

Throughout both videos `keyd-application-mapper` isn't running and I am holding <kbd>capslock</kbd> to activate the `CapsLayer` layer.

__First video explanation:__ At 0:06-0:11 I move normally by holding <kbd>j</kbd> and <kbd>;</kbd>, then at 0:12-0:17 I do it again but while holding <kbd>j</kbd>/<kbd>;</kbd> also briefly tap <kbd>d</kbd> to activate the shift layer, which causes the <kbd>control</kbd> layer to also activate, resulting in <kbd>C-left/right</kbd> movements. Then at 0:19-0:26, I hold <kbd>j</kbd>, hold <kbd>;</kbd>, then release <kbd>j</kbd> which causes the <kbd>control</kbd> layer to activate and <kbd>C-right</kbd> inputs are sent, and after the cursor stops, I hold <kbd>;</kbd>, hold <kbd>j</kbd>, then release <kbd>;</kbd> which also causes the <kbd>control</kbd> layer to activate and <kbd>C-left</kbd> inputs are sent. The rest of the video is me showing the doing the same thing with the <kbd>k</kbd> and <kbd>l</kbd> keys instead, which results in the same problem.

__Second video explanation:__ I hold down <kbd>d</kbd> to activate the shift layer, then also hold a layer's movement keys [<kbd>jkl;</kbd>], which works as expected, until <kbd>d</kbd> is released at which point <kbd>C-up/down/left/right</kbd> are sent

**Comment by rvaiya** [comment] 2022-05-02 09:59
This is expected behaviour. The layers only apply on key down, you can't alter them mid-press. What is your use case? Does this present a real usage issue?

**Comment by i-c-u-p** [comment] 2022-05-02 10:32
> This is expected behaviour. The layers only apply on key down, you can't alter them mid-press. What is your use case? Does this present a real usage issue?

I would imagine it's a usage issue since the `CapsLayer`'s movement keys were having ctrl applied to them even though spacebar or the literal ctrl key were never pressed. I'm not sure if it's what most users would expect either, especially the second video where letting go of <kbd>d</kbd> applied ctrl and the cursor went flying off.

**Comment by rvaiya** [comment] 2022-05-02 17:09
> I would imagine it's a usage issue since the CapsLayer's movement keys were
> having ctrl applied to them even though spacebar or the literal ctrl key were
> never pressed.

Your capslock layer specifies the control key in its mod set. This is only deactivated
for `j` not for other layer keys like `d`.

> I'm not sure if it's what most users would expect either,
> especially the second video where letting go of d applied ctrl and the cursor
> went flying off.

Having layers retroactively apply to held keys would cause other problems and is
arguably more unintuitive.  No other remapping software I am aware of does this.

**Comment by rvaiya** [comment] 2022-05-03 21:30
I'm closing this for now. Feel free to reopen it if you feel the issue is unresolved.

**Closed by rvaiya** 2022-05-03 21:31 UTC
