### ISSUE TITLE
Support for nested modifier layers.

### ISSUE THREAD

**Issue by juligreen** [rvaiya/keyd#69] opened 2021-12-13 20:53 UTC
The feature might also not work as advertised (or I might misunderstand something).

Minimal reproducible config:
```
capslock = layer(custom_control)
shift = layer(custom_shift)

[custom_shift:S]
capslock = swap(custom_control_shift)

[custom_control:C]
shift = swap(custom_control_shift)

[custom_control_shift:C-S]
. = C-tab
, = C-S-tab
```

C-tab and C-S-tab should work the same way as before but they don't.

If you hold capslock and press tab it works as usual. (only C-tab is pressed, it goes to the right tab in the browser)
If you hold capslock and tap shift once and press tab afterwards it works like C-S-tab even though only C-tab is pressed (meaning it goes to the left tab in the browser).

The documentation says `The supplied layer is active for the duration of the depression of the current layer's activation key` which seems to differ from my findings

Thank you for any support!

**Comment by juligreen** [comment] 2021-12-13 21:03
After reading one more time, it seems like this is the intended functionality of swap.
Therefore I'm going to try to explain the problem I was trying to solve with swap.

This is my original config:

**Comment by juligreen** [comment] 2021-12-13 21:04
Sorry for the unintentional close

**Comment by lemnos** [comment] 2021-12-14 01:08
Thanks for the comprehensive example.

Unfortunately nested modifier layers are unsupported. Modifier layers behave as modifiers *first* and layers second. That is, pressing two keys bound to modifier layers in combination should always yield the combination of those modifiers.

To take a minimal example

```
leftalt = layer(alt)
capslock = layer(capslock)

[alt:A]

capslock = layer(capslock+alt)

[capslock:C]

alt = layer(capslock+alt)

[capslock+alt:S]
```

**Should** always cause `capslock + alt` to behave as control and alt. For implementation related reasons it may or may not actually do this under the above config since `alt = layer(capslock+alt)` attempts to remap one modifier within a another, resulting in undefined behaviour.

Part of the reason for this is because trying to do this sort of nested mapping inherently introduces ambiguity.

Consider what happens when a third modifier is introduced: `M`. What should happen when the user presses `capslock+alt+meta`? There are two possible interpretations under the above config: `M-A-C` or `M-S`. This is confusing for the user who might reasonably expect the combination of modifiers to always be the union of said modifiers. Additionally, many applications rely on modifiers being used in combination, making remapping their combinations a fraught business (How does the user press `A-C-1` under the above config?).

The purpose of modifier layers then is to override a small subset of modified keys. This must be used judiciously in order to avoid conflicts and keep your modifiers useful.

Having said that, you are of course free to define your own (non modifier) nested layers which simulate this behaviour.

E.G

```
alt = layer(myalt)
...
[myalt]
capslock = layer(capslock+alt)
a = A-a
b = A-b
c = A-c
...
```

The problem with this is that you end up sacrificing the other combinatorial properties of modifiers like alt.

For this reason, I generally try and avoid extensively remapping my modifiers keys, instead favouring a nav layer actuated with a single key.

When you first encounter the ability to remap modifiers it is tempting to try and remap *all the things*, but when you invariably need to press `A-C-M-k` to make emacs ferry your dead grandma across the river styx, you will soon find yourself shaking your fist at the heavens.

Admittedly this is all poorly documented, a thing I hope to remedy in the upcoming 2.0 release (which will likely also change some of this undefined behaviour).

**Comment by juligreen** [comment] 2021-12-14 13:05
Thank you for the reply!

> Having said that, you are of course free to define your own (non modifier) nested layers which simulate this behaviour.

I tried this very thing with komonad (as it was also the only way to achive my layout there, but I encountered an issue where I couldn't use <control> with the mousewheel to scroll anymore (see https://github.com/kmonad/kmonad/issues/430). I assume I would encounter the same issue here.

> Should always cause capslock + alt to behave as control and alt. For implementation related reasons it may or may not actually do this under the above config since alt = layer(capslock+alt) attempts to remap one modifier within a another, resulting in undefined behaviour.

I'd argue that with `[capslock+alt:S]` capslock and alt should always behave like shift, even if combined with other modifiers, as the user explicitly wrote that capslock+alt = shift. The user should then have the responsibility to map capslock+alt to some other key.

I'm going to outline my usecase further here:
I've been using xkeysnail until now and I'm now trying to migrate to a wayland-compatible key-rebinding daemon to prepare for my move to wayland in the future.

My xkeysnail config:
```python
# -*- coding: utf-8 -*-

from xkeysnail.transform import *

# [Global modemap] Change modifier keys as in xmodmap
define_modmap(
    {
        Key.CAPSLOCK: Key.LEFT_CTRL,
    }
)

# Emacs-like keybindings in non-Emacs applications
define_keymap(
    lambda wm_class: wm_class
    not in (
        "Emacs",
        "Zathura",
    ),
    {
        K("C-Shift-dot"): K("C-TAB"),
        K("C-Shift-comma"): K("C-Shift-TAB"),
        K("C-b"): K("left"),
        K("C-M-b"): K("C-b"),
        K("C-f"): K("right"),
        K("C-M-f"): K("C-f"),
        K("C-p"): K("up"),
        K("C-n"): K("down"),
        K("C-h"): K("backspace"),
        K("M-b"): K("C-left"),
        K("M-f"): K("C-right"),
        K("M-Shift-f"): K("M-f"),
        K("C-a"): K("home"),
        K("C-M-a"): K("C-a"),
        K("C-e"): K("end"),
        K("C-M-e"): K("C-e"),
        K("C-m"): K("enter"),
        K("C-M-m"): K("C-m"),
        K("C-Shift-m"): K("Shift-enter"),
        K("C-w"): [K("C-backspace"), set_mark(False)],
        K("C-M-w"): K("C-w"),
        K("C-d"): [K("delete"), set_mark(False)],
        K("C-M-d"): [K("C-d"), set_mark(False)],
        K("M-d"): [K("C-delete"), set_mark(False)],
        K("C-k"): [K("Shift-end"), K("backspace"), set_mark(False)],
        K("C-Super-k"): K("C-k"),
    },
    "Emacs-like keys",
)
```

With this config I'm able to achive exactly what I want, mapping emacs like keybinds to the base layer of my ctrl/capslock key and moving the original binds one layer down into the ctrl+alt layer.

I assume this doesn't translate to keyd too well since I was able to map keys+modifiers directly and didn't have to use layers?

> When you first encounter the ability to remap modifiers it is tempting to try and remap all the things, but when you invariably need to press A-C-M-k to make emacs ferry your dead grandma across the river styx, you will soon find yourself shaking your fist at the heavens.

With xkeysnail I was able to exclude programs from my config by their wm-class.
This won't be possible with wayland as the wm-classes don't exists and you don't have access to use them anyway.

My workaround for this would be use another layer (i.e. bind the layout function to a key) which has the normal keybinds and activate it when inside a game or a program like emacs (usually I use vim so it's normally not a problem.
In kmonad I was even able to bind this layout-switching to double or triple tapping right control.


Mind you, I'm not expecting for keyd to cover my use-case if it's not build for that, I just wanted to put it out there if someone else is trying to achive the same thing :v:

**Comment by rvaiya** [comment] 2021-12-14 20:13
> I tried this very thing with komonad (as it was also the only way to achive my layout there, but I encountered an issue where I couldn't use with the mousewheel to scroll anymore (see kmonad/kmonad#430). I assume I would encounter the same issue here.

This is part of the reason modifier layers exist. As soon as they are activated the corresponding modifiers get depressed which allows you to do things like use them in combination with the mouse.

> I'd argue that with [capslock+alt:S] capslock and alt should always behave like shift, even if combined with other modifiers, as the user explicitly wrote that capslock+alt = shift. The user should then have the responsibility to map capslock+alt to some other key.

Right now the rules for looking up key actions are as follows:

  1. If one layer is active:
	If the next key is mapped:
		Use the provided mapping
	else if it is a modifier layer:
		Behave as the corresponding modifier set
  2. If more than one non modifier layer is active use the most recently activated layer.
  3. If more than one modifier layer is active the result is the combination of the assigned layer modifiers
  4. If some combination of non modifier and modifier layers are active the results are undefined

While it would be possible to modify `3` to examine all subsets of currently active layers and intelligently resolve what the new modifier should be (i.e disambiguate `control+alt` = `S` and `control+alt+super` = `C-A-M`), this is almost certainly a bad idea.

Part of the definition of a modifier is that it is composable with other modifiers. Specifically, one or more of them *always* combine to produce their sum. 

This is central to the user's intuition of how modifiers work (see also #32).  Almost every program relies on this behaviour, so even if you think you won't need it now, when you run jetbrain's fancy new IDE for the first time (god forbid) you don't want to find that `C-M-j` doesn't work because your control and alt keys have decided to have shifty offspring.

Modifer layers *are* modifiers and modifiers have well defined behaviour. Layers by contrast are entirely user defined. They are free to combine in whatever way the user desires, but they are not modifiers.

A compromise, which would accomodate your particular use case, would be to allow non modifier layers to be nested within modified ones and always have them take precedence. That is `4` could be modified to:

 - If some combination of non modifier layers and modifier layers are active then the most recently active layer takes precedence.

Thus making the following config valid:

```
[capslock:C]
leftalt = layer(capslock+alt)

[alt:A]
capslock = layer(capslock+alt)

[capslock+alt]
a = S-a
b = S-b
w = C-backspace
...
```

This would still be a bad idea for the reasons outlined above, but it wouldn't drastically complicate the state machine and would make use of presently undefined behaviour.

> I've been using xkeysnail until now and I'm now trying to migrate to a wayland-compatible key-rebinding daemon to prepare for my move to wayland in the future.

Application specific rebinding will probably be supported in 2.0. See #51.

> With this config I'm able to achive exactly what I want, mapping emacs like keybinds to the base layer of my ctrl/capslock key and moving the original binds one layer down into the ctrl+alt layer.
>
> I assume this doesn't translate to keyd too well since I was able to map keys+modifiers directly and didn't have to use layers?

I considered allowing keysequences to be valid left hand values when designing keyd (e.g `C-k = foo`). The problem is that you almost never want to to overwrite the modifiers themselves (e.g you want to remap your capslock key but not your control key). I'm curious to know how that config handles `capslock+alt+shift+d`. Making nesting work as you describe would be the correct solution.

> With xkeysnail I was able to exclude programs from my config by their wm-class.
> This won't be possible with wayland as the wm-classes don't exists and you don't have access to use them anyway.

There are workarounds for this (e.g app ids). I will probably add some kind of third party support for application awareness accross the different platforms.

> In kmonad I was even able to bind this layout-switching to double or triple tapping right control.

If you really want to achieve this in keyd you can do it with nested layering.

E.G

```
rightcontrol = control1

[control1:C]
rightcontrol = oneshot(layer2)
...
[layer2]
rightcontrol = oneshot(layer3)
...
[layer3]
...
```

Naturally I advise against this :P

> Mind you, I'm not expecting for keyd to cover my use-case if it's not build for that, I just wanted to put it out there if someone else is trying to achive the same thing ✌️

No, this is useful feedback for 2.0. Feel free to keep iterating, it helps me hammer out the design and forces me to document my process. One of the goals of keyd is to make common things easy and hard things possible without the user having to resort to a turing complete language or think about individual key events.

**Comment by rvaiya** [comment] 2021-12-21 20:44
To distill it (for the sake of us both :P):

The fundamental problem is that keyd treats all layers equally. Consider the following configs:

```
alt = layer(myalt)
control = layer(mycontrol)

[myalt:A]

[mycontrol:C]
```

```
alt = layer(myalt)

[myalt:A]
control = layer(mycontrol)

[mycontrol:C]
```


Both of them have the same meaning in the case of `alt` + `control`, namely:

activate the `mycontrol` *and* `myalt` layers. 

The end result is that `A-C` becomes the active modifier set. This is consistent with the traditional approach of treating layers
as a stack of occluding keymaps while simultaneously preserving the behaviour of the modifiers these layers represent.

If you want these cases to be treated differently then you have to propose an alternative model for layer activation. It is not immediately obvious what such a model would look like, but I am not necessarily opposed to implementing it, if it is proposed and a good case made for it.

One possibility might be to maintain a tree of layers and only apply modifiers in siblings of the currently active leaf node, thereby giving layers a degree of context awareness.

The problem with this approach is that it makes the state of the keyboard harder to reason about and can produce other untuitive outcomes.

It is worth noting that most other remappers don't have to contend with this issue by virtue of simply not having any support for hybrid layers. The problem only materializes when you are trying to reconcile the idea of a modifier with the idea of a layer since you have to take stacking semantics into account. keyd takes a 'modifier first' approach to its modifier layer implementation, preserving modifier semantics at all costs and allowing them to be selectively overwritten when necessary.

**Comment by rvaiya** [comment] 2021-12-27 18:16
The latest commit clarifies this undefined behaviour and changes rule 4 as outlined in my second post. As a result your original config should now work mostly unaltered (see the changelog for details). Let me know if you have any issues.

**Comment by juligreen** [comment] 2021-12-27 20:38
Sorry for not replying until now.

Thank you for this amazing effort, this really seems to work exactly as I want it to!

Do you need more feedback on this?

**Comment by rvaiya** [comment] 2021-12-28 03:28
No worries. Feedback is always appreciated. I'm closing this for now, but feel free to create another issue if you encounter a problem.

**Closed by rvaiya** 2021-12-28 03:28 UTC
Labels: documentation, enhancement, 2.0
