### ISSUE TITLE
How to make repeatable pause key on hold down?

### ISSUE THREAD

**Issue by llybin** [rvaiya/keyd#657] opened 2024-02-04 13:47 UTC
Hello.
When you use mc file manager holding Insert down allows to select row by row, without pressing on every row.
But remapped key has't this repeating behavior. Can I somehow fix this?

My config:
``` ini
[ids]
*
[main]
# Remaps the pause key to insert
pause = insert
```

**Comment by nsbgn** [comment] 2024-02-04 13:59
I can't reproduce this. For me, `insert` has the same effect whether it's the real `insert` key or the remapped `pause` key. This is also what I would expect, since what's emitted by the virtual keyboard should be indistinguishable to `mc`. What does `keyd monitor` show when you press the real vs the remapped key?

For now, you may be able to use `pause = macro2(120, 80, insert)` (with timeouts to taste) to force a key repeat (though it shouldn't be necessary).

**Comment by llybin** [comment] 2024-02-04 14:24
keyd monitor show:
```
# original
keyd virtual keyboard   0fac:0ade       insert down
keyd virtual keyboard   0fac:0ade       insert up
# remapped
keyd virtual keyboard   0fac:0ade       insert down
keyd virtual keyboard   0fac:0ade       insert up
```
`pause = macro2(120, 80, insert)` that didn't help either. I not forgotten to reload :) 

Video proof: https://photos.app.goo.gl/BeqEATZaLvzb4Dc59

I had the same behavior with xmodmap, I thought I hadn't configured something properly. I've remapped other key on insert and it works expected. Probably it's some specific of my keyboard and the pause key. Thanks for answer! Probably you can close the ticket.

**Comment by rvaiya** [comment] 2024-02-04 18:59
In the above output, can you indicate where you physically release the key? The output looks identical.

**Comment by llybin** [comment] 2024-02-04 19:49
output is identical yep. when I press a key "insert down" when I release a key getting "insert up"
Everything is the same excluding it's not repeats, exactly on the "pause" key 🤷‍♂

**Comment by rvaiya** [comment] 2024-02-04 22:59
Does this happen when you remap other keys to insert, or only pause? Also, are you running this in a virtual console? Unlike display servers, which generate their own repeat events, the virtual console relies on repeat events from the input driver. My suspicion is that this has something to do with the kernel not generating repeat events for pause.

**Comment by llybin** [comment] 2024-02-05 09:45
> Does this happen when you remap other keys to insert, or only pause?
I haven't checked all the keys. It definitely doesn't work on pause. It works on the other two random ones.

> Also, are you running this in a virtual console?
I checked both, same behavior.

Probably they have fixed the problem xD https://www.asus.com/support/faq/1041927/

**Comment by rvaiya** [comment] 2024-05-03 22:08
> I haven't checked all the keys. It definitely doesn't work on pause. It works on the other two random ones.

Closing, since this is likely a hardware bug. Feel free to reopen it.

**Closed by rvaiya** 2024-05-03 22:08 UTC
