### ISSUE TITLE
P key stopped producing lower p

### ISSUE THREAD

**Issue by Kerbiat** [rvaiya/keyd#407] opened 2022-12-26 08:14 UTC
### Issue
P key stopped producing lower p symbol.

_xev return when i press p:_
```
FocusOut event, serial 110, synthetic NO, window 0x2400001,
    mode NotifyGrab, detail NotifyAncestor

MappingNotify event, serial 110, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

MappingNotify event, serial 111, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

FocusIn event, serial 111, synthetic NO, window 0x2400001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 111, synthetic NO, window 0x0,
    keys:  68  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
```
`sudo keyd monitor` shows p key being pressed.
Deleting or clearing [main] in `/etc/keyd/default.conf` and running `sudo keyd reload` didn't help.
`sudo journalctl -eu keyd` showed no errors. 
Killing keyd process didn't help.
Adding p = p to [main] in `/etc/keyd/default.conf` didn't work.

p + any modifiers produces normal results.
Binding p to any other symbol works.
### Context
Yesterday i installed keyd and played around with it. `/etc/keyd/default.conf` is the only file i was changing. At the end of the day i cleared [main] layer and turned off pc. Only today i found that p key acts the way it does.
### PS
I really don't know how i did this. Maybe i missed something. I don't know how to interpret the message that xev gives on p press and i have no clue how to fix this. I will probably just backup my system and install keyd again so i don't really need a solution yet i decided to write about it.

**Comment by slakkenhuis** [comment] 2022-12-26 11:32
That is really odd. I'm not the dev for keyd, but just to be clear: your default.conf is completely empty now? If even stopping keyd (that is, turning off the keyd service and rebooting) doesn't fix the issue, I'm inclined to suspect that it's a coincidence and the issue lies elsewhere. Can you use the keyboard on another computer?

**Comment by Kerbiat** [comment] 2022-12-26 16:11
I backed my system so i don't have this issue now. The thing that might've caused that issue is that i had problems installing keyd. I didn't have c-compiler installed when i tried to `make install` keyd first time. I used `make uninstall` and reinstalled keyd after installing gcc. I might've messed something up on that step but i didn't notice any problems after install. Maybe i messed something up on installation and the problem occurred only after pc reboot because i don't remember any problems yesterday yet today once i started my pc i noticed problem with p character quite quickly.

Anyway, i don't know what it was. I fixed issue by backing my system and installing keyd first try this time so i'm happy.

**Comment by rvaiya** [comment] 2022-12-26 20:23
> sudo keyd monitor shows p key being pressed.

Which suggests the key is propagating through to evdev so the issue is higher up the input stack (i.e not keyd)

> Killing keyd process didn't help.

Which would corroborate the above.

I'm closing this as it doesn't appear to be a keyd issue.

**Closed by rvaiya** 2022-12-26 20:23 UTC
