### ISSUE TITLE
application-mapper: always reset after switching away from application?

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#102] opened 2022-01-16 05:26 UTC
Right now, `keyd-application-mapper` will happily add `-e` expressions when switching _to_ an application. However, when switching _away_ from an application, the app-specific mapped keys remain in force (unless you happen to switch to another application whose mapped keys override the former).

Would it make sense to always send a 'reset' when switching away from an app? This is the configuration that's working for me:

```
    subprocess.run(['keyd', '-e', 'reset'])
    if cls in bindings:
        # Apply the bindings.
        subprocess.run(['keyd', '-e', *bindings[cls]])
```

My use case: the only app I'm currently re-mapping keys for is `gnome-terminal`. I'm mapping `M-c` to `C-S-c` for copy, and `M-v` for paste for example. Then when switching away (to any other app), these expressions should be reset.

**Comment by rvaiya** [comment] 2022-01-16 05:42
Yes, this is a known problem. The issue with doing a simple reset at the moment is is that it triggers a key up of all currently depressed keys by design. A consequence of this is that if the user has used a key combination (like alt+tab) to change the active window it will render subsequent actuations ineffective until the next key up. Properly fixing this requires allowing bindings to be hot swapped in place which requires some non trivial internal changes (that are in the pipeline).

P.S

You can do `keyd -e "reset" "binding1" "binding2"' rather than creating another subprocess.

**Comment by canadaduane** [comment] 2022-01-16 14:11
Oh good to know!

> You can do keyd -e "reset" "binding1" "binding2" rather than creating another subprocess.

Yes, but this would only be triggered if the `cls` is in `bindings`. That wouldn't work when you move focus to an application that keyd does not have bindings for. Perhaps the "right way" to reset would be this then:
```
    if cls in bindings:
        # Apply the bindings.
        subprocess.run(['keyd', '-e', 'reset', *bindings[cls]])
    else:
        subprocess.run(['keyd', '-e', 'reset'])

```

**Comment by rvaiya** [comment] 2022-01-17 04:43
This should be fixed in the latest commit.

**Closed** 2022-01-18 00:44 UTC
