### ISSUE TITLE
keyd-application-mapper -d does not start when the OS boot

### ISSUE THREAD

**Issue by shungo27** [rvaiya/keyd#161] opened 2022-03-21 14:09 UTC
This may be due to using the Apple Wireless Keyboard. When I checked the log, I got the following message.
```
could not connect to keyd instance, make sure it is running and you are a member of'keyd'
```
Comment out `ping_keyd()` of keyd-application-mapper, it will be autostart. Or manually run `keyd-application-mapper -d` after the keyboard has a Bluetooth connection.

keyd 2.3.0-rc
gnome 3.38

**Comment by rvaiya** [comment] 2022-03-21 20:25
To clarify, does this problem occur only on boot? If keyd-applicaiton-mapper is started before keyd (this shouldn't happen) it will fail to start. How are you starting `keyd-application-mapper`? I assume you are using shipped systemd file for keyd initialization.

**Comment by shungo27** [comment] 2022-03-22 10:16
The installation was done according to README.md. keyd-application-mapper starts as a Gnome extension.

/lib/systemd/system/keyd.service
```
[Unit]
Description=key remapping daemon
Requires=local-fs.target
After=local-fs.target

[Service]
Type=simple
ExecStart=/usr/bin/keyd
ExecReload=/bin/kill -USR1 $MAINPID

[Install]
WantedBy=sysinit.target
```

The only physical inputs on my system are a Bluetooth keyboard and a Bluetooth trackpad.

After booting the OS, the "keyd -e ping" command doesn't seem to return "pong". Because the Bluetooth connection isn't established until I press any key.

When the keyboard is connected, "keyd -e ping" will return "pong".

I tested keyd -e ping on an ssh connection.

**Comment by rvaiya** [comment] 2022-03-23 03:39
Thanks for the additional details :). It looks like a regression was introduced which made ping dependent on the presence of a keyboard. This should be fixed in the latest commit.

**Comment by rvaiya** [comment] 2022-03-26 02:15
I'm closing this for now. Feel free to reopen it if the issue remains unresolved.

**Closed by rvaiya** 2022-03-26 02:15 UTC

**Comment by shungo27** [comment] 2022-03-26 03:05
perfect 👍👍👍
