### ISSUE TITLE
Enter keeps pressing and then doesn't work

### ISSUE THREAD

**Issue by raffaem** [rvaiya/keyd#198] opened 2022-04-27 12:36 UTC
Whenever I start the service from the terminal, the enter key is likes is constantly pressed and released.

If I close the terminal with alt+f4 and restart it, the enter key does not work anymore.

I have to use the enter from my numpad, like i'm doing right now

**Comment by rvaiya** [comment] 2022-04-30 02:25
I believe this should be fixed in the latest commit. Confirmation would be appreciated.

**Comment by rvaiya** [comment] 2022-05-03 21:31
I'm closing this for now. Feel free to reopen it if the issue is unresolved.

**Closed by rvaiya** 2022-05-03 21:31 UTC
