### ISSUE TITLE
Switch layout to ctrl

### ISSUE THREAD

**Issue by KOT040188** [rvaiya/keyd#405] opened 2022-12-17 17:43 UTC
Hello, is it possible to use keyd to assign layout switching to the left ctrl and so that combinations with ctrl work?

**Comment by slakkenhuis** [comment] 2022-12-17 18:00
Do you mean this?

```
leftcontrol = overload(control, setlayout(...))
```

**Comment by KOT040188** [comment] 2022-12-17 19:01
Perhaps I do not quite understand how to configure keyd. I created a /etc/keyd/default.conf file and added the following text to it:
`[ids]
*
[main]
leftcontrol = overload(control, setlayout(...))`
After that I ran the command:
`kot@192:~$ sudo keyd reload
usage: keyd [option]

Options:
    -m, --monitor      Start keyd in monitor mode.
    -l, --list-keys    List key names.
    -v, --version      Print the current version and exit.
    -h, --help         Print help and exit.
`
But I didn't get what I wanted. And the output of the command is quite strange. I still can't switch layouts with the ctrl key.

**Comment by slakkenhuis** [comment] 2022-12-17 20:11
`setlayout(...)` was intended as a shorthand for the layout you want to switch. (`...` is not a valid layout itself; a full example would also define your desired layouts and refer to them rather than to `...`. Please see the manual section on layouts for details.)

The question was mostly to clarify what you're asking.

I assume you mean to to use control normally, except that when pressed in isolation, it activates Colemak (or similar) when in Qwerty or Qwerty when in Colemak.

You can do this by combining `overload` with an action that changes your layout (`setlayout`) or layer (`toggle`). The easiest way probably looks something like:

```
[ids]
*

[colemak]
a = b
# Etcetera

[main]
leftcontrol = overload(control, toggle(colemak))
```

Does that help?

Also, from the output of your `keyd` command, I see that you're running a version that doesn't have the `reload` subcommand. Are you able to update to the latest version?

(It's good practice to mention the version that you're running, as well as what you've tried/where the manual was unclear.)

**Comment by KOT040188** [comment] 2022-12-17 20:36
>Also, from the output of your keyd command, I see that you're running a version that doesn't have the reload subcommand. Are you able to update to the latest version?

This is the latest version in the opensuse tumbleweed repository https://build.opensuse.org/package/show/openSUSE%3AFactory/keyd I don't think I can handle compiling from source.

>[ids]
>*

>[colemak]
a = b
># Etcetera

>[main]
leftcontrol = overload(control, toggle(colemak))

It's already night now.  I will check this setting option tomorrow.

**Comment by KOT040188** [comment] 2022-12-18 13:01
>You can do this by combining overload with an action that changes your layout (setlayout) or layer (toggle). The easiest way probably looks something like:

I saved the new settings and rebooted the PC. Does not work, the layout does not switch.

**Comment by slakkenhuis** [comment] 2022-12-18 14:47
> I don't think I can handle compiling from source.

Alright --- you're on the latest stable version, so don't worry about it. (That said, no need to be too intimidated: the prerequisites are fairly ubiquitous, so you likely don't need to do much more than run `make` and `sudo make install`.)

> Does not work, the layout does not switch.

Could you tell me what you're trying to achieve? For example, what exactly do you mean by layout? What did you try --- since the suggestion I gave is a skeleton solution that you'd need to extend with your desired behaviour? What was the error message (`sudo journalctl --no-pager -eu keyd`)?

**Comment by KOT040188** [comment] 2022-12-18 14:49
Maybe I didn't describe the task exactly. I need the ctrl key to switch keyboard layouts ru / en and that other combinations with ctrl work at the same time.

**Comment by KOT040188** [comment] 2022-12-18 14:52
```
kot@192:~$ sudo journalctl --no-pager -eu keyd
сне 18 15:27:16 localhost systemd[1]: Started key remapping daemon.
сне 18 15:27:16 localhost keyd[1299]: Starting keyd v2.4.2 ()
сне 18 15:27:16 localhost keyd[1299]: socket: /var/run/keyd.socket
сне 18 15:27:16 localhost keyd[1299]: device added: 1e7d:303e ROCCAT ROCCAT HORDE AIMO (/dev/input/event7)
сне 18 15:27:16 localhost keyd[1299]:         matched /etc/keyd/default.conf
сне 18 15:27:16 localhost keyd[1299]: device added: 1e7d:2e4b ROCCAT ROCCAT Tyon White (/dev/input/event5)
сне 18 15:27:16 localhost keyd[1299]:         matched /etc/keyd/default.conf

```

**Comment by KOT040188** [comment] 2022-12-18 15:22
I now understand that `leftcontrol = overload(control, toggle(colemak))` works, but it doesn't do what I want.

**Comment by slakkenhuis** [comment] 2022-12-18 15:44
I see. I'll clarify.

A "layout" is a slippery concept --- your keyboard doesn't emit characters directly, but only *keycodes*. The way they are subsequently interpreted is dependent on your display environment.

`keyd` works around that by using *compose sequences*. keyd will emit a sequence of keycodes that corresponds to the Unicode character that you want to type. **This requires that your compose key is set (see the manual).** You would manually define a secondary layer: for each key on the left-hand side (the name of which you can figure out using `keyd --monitor`), you set a symbol on the right-hand side:

```
[ids]
*

[ru]
d = д
# continue with the rest of your keys

[main]
leftcontrol = overload(control, toggle(ru))
```

However, what I suspect you mean when you say 'layout' is your *display environment's* interpretation of keycodes. Is that correct? In general, **it's recommended to handle everything through `keyd`, rather than mixing these concepts and getting confused**. However, it's not impossible. For example, I think that in Gnome, `Super+Space` changes your layout, so you could do:

```
[main]
leftcontrol = overload(control, M-space)
```

However, again, this is dependent on what you use (X11, KDE/Gnome on Wayland, Sway, etcetera).

**Comment by KOT040188** [comment] 2022-12-18 16:28
>leftcontrol = overload(control, toggle(ru))

This does not work.

>I think that in Gnome, Super+Space changes your layout, so you could do:

I'm using kde, but my keyboard layout switch is set to Super+Space.

leftcontrol = overload(control, M-space)

And it works! Thank you! As I understand it, you can assign any combination and register it in the settings? For example alt+shift or something else.

**Comment by slakkenhuis** [comment] 2022-12-18 16:49
> This does not work.

Can't troubleshoot that without knowing what specific steps you took, but I suppose it doesn't matter if you decided to go the other route.

> As I understand it, you can assign any combination and register it in the settings?

`keyd` emits keys that are then interpreted by KDE, so yes --- you can set whatever combination of keys, as long as they correspond. (`alt+shift` doesn't work, though, because those are two modifiers, not a modifier and a key.)

Please close the issue if it's resolved :)

**Closed** 2022-12-18 19:06 UTC
