### ISSUE TITLE
External keyboard on FreeBSD

### ISSUE THREAD

**Issue by ItsNilDev** [rvaiya/keyd#412] opened 2023-01-04 09:42 UTC
Keyd doesn't detect nothing from external keyboard on FreeBSD. It works fine on linux.
Even `keyd --monitor` shows nothing.

**Comment by tkna91** [comment] 2023-01-05 10:16
The command should officially be `keyd monitor`, but currently keyd is only supported on linux, and FreeBSD should not be supported.

@rvaiya Please consider whether FreeBSD can be made eligible for support.

**Comment by ItsNilDev** [comment] 2023-01-25 15:13
So, to add some notes here, the latest stable version in freebsd is the 2.4.2, which is what i'm using, so the command line for that should be `keyd --monitor`.
The problem with external key boards is that keyd doesn't detect them at all as you can see the output below
```
$ keyd --monitor
 device added: 0000:0000 (System mouse)
device added: 0000:0000 (System keyboard multiplexer)
device added: 0001:0001 (AT keyboard)
device added: 0fac:0ade (keyd virtual device)
device added: 0fac:1ade (keyd virtual pointer)
```
and it is missing the 
```
$ sysctl -a | grep evdev
kern.evdev.input.7.phys: ukbd0
kern.evdev.input.7.id: { bustype = 0x0003, vendor = 0x1c4f, product = 0x0026, version = 0x0000 }
kern.evdev.input.7.name: SIGMACHIP USB Keyboard, class 0/0, rev 1.10/1.10, addr 8
```
I then tried to put the ids manually and again, it worked with laptop's key board but not the external one.
The last thing i tried to do was building it manually from source with gmake. but it  was complaining about the absence of the bind package, so i didn't bother to use it afterwards.

**Comment by tkna91** [comment] 2023-01-30 07:54
Indeed, the package seems to exist on FreeBSD.

- https://pkgs.org/search/?q=keyd
- https://freebsd.pkgs.org/13/freebsd-amd64/keyd-2.4.2.pkg.html

Maybe the package definition does not specify the appropriate dependent package, etc.?
I feel it would be appropriate to discuss this with the package maintainer first, not here.

**Comment by jbeich** [comment] 2023-02-25 08:40
Duplicate of #261. [Applied](https://github.com/freebsd/freebsd-ports/commit/04e8cb87e9bf) downstream as it isn't part of any tag yet.

**Comment by ItsNilDev** [comment] 2023-03-01 06:10
It worked! thanks yall
btw, when will the next version hit?

**Closed** 2023-03-01 06:12 UTC
